In [51]:
import pandas as pd
import numpy as np

In [52]:
sf_permits = pd.read_csv("../dataset/building-permit-applications-data/Building_Permits.csv")

/home/neil/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [53]:
sf_permits

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
5,201706149344,8,otc alterations permit,06/14/2017,4105,009,800,NaN,Indiana,St,...,1.0,constr type 1,1.0,constr type 1,NaN,10.0,Potrero Hill,94107.0,"(37.75922331346539, -122.39170402628598)",1466911170855
6,201706300814,8,otc alterations permit,06/30/2017,1739,020,1291,NaN,11th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Inner Sunset,94122.0,"(37.764145640138565, -122.46875112470363)",1468970403692
7,M803667,8,otc alterations permit,06/30/2017,4789,014,1465,NaN,Revere,Av,...,NaN,NaN,NaN,NaN,NaN,10.0,Bayview Hunters Point,94124.0,"(37.73005099023611, -122.38784938916618)",1469035175050
8,M804227,8,otc alterations permit,07/05/2017,1212,054,2094,NaN,Fell,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.772393498502595, -122.45231466824669)",1469198253772
9,M804767,8,otc alterations permit,07/06/2017,1259,016,89,NaN,Alpine,Tr,...,NaN,NaN,NaN,NaN,NaN,8.0,Haight Ashbury,94117.0,"(37.7691724293766, -122.43734859051908)",146932394171
10,M805287,8,otc alterations permit,07/06/2017,3541,001,106,NaN,Sanchez,St,...,NaN,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.767349757757145, -122.43140682973024)",1469445246849
11,M805907,8,otc alterations permit,07/07/2017,0829,021,675,NaN,Fell,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102.0,"(37.774914087334544, -122.42886839796792)",146961582526
12,M806447,8,otc alterations permit,07/10/2017,6537,023,4082,NaN,25th,St,...,NaN,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.75006779619502, -122.43127350268124)",1469781206718
13,201707252846,8,otc alterations permit,07/25/2017,6589,002R,681,NaN,27th,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Noe Valley,94131.0,"(37.7462205625642, -122.4353484860549)",1471799208305
14,M813729,8,otc alterations permit,07/26/2017,1049,027,2761,NaN,Pine,St,...,NaN,NaN,NaN,NaN,NaN,2.0,Pacific Heights,94115.0,"(37.78676200041077, -122.44124093333335)",147203988249
15,M813907,8,otc alterations permit,07/27/2017,0243,043,840,NaN,Powell,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Chinatown,94108.0,"(37.7926690651263, -122.40883941791454)",147208763456
16,M813967,8,otc alterations permit,07/27/2017,0268,008,220,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Financial District/South Beach,94104.0,"(37.79130641988351, -122.40198579459195)",147211866168
17,M814148,8,otc alterations permit,07/27/2017,3621,097,3707,NaN,21st,St,...,NaN,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.75607840165479, -122.43041143390109)",1472184412108
18,201707283165,8,otc alterations permit,07/28/2017,0472,042,1307,NaN,Bay,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.8035183252307, -122.42863180996076)",1472277302360
19,M814368,8,otc alterations permit,07/28/2017,2659,001,263,NaN,Corbett,Av,...,NaN,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.761092365437214, -122.44402154957145)",1472295408612
20,M814967,8,otc alterations permit,07/31/2017,1176,068,1624,NaN,Fulton,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77640228859421, -122.44361679686382)",1472619503582
21,201708013476,8,otc alterations permit,08/01/2017,6529,010,3410,NaN,26th,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Mission,94110.0,"(37.74914175355125, -122.41849211166853)",1472727381751
22,201708013544,3,additions alterations or repairs,08/01/2017,0074,043,2150,NaN,Taylor,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Russian Hill,94133.0,"(37.802405951667645, -122.41446286561653)",147281357792
23,M816927,8,otc alterations permit,08/07/2017,0941,012,2824,NaN,Filbert,St,...,NaN,NaN,NaN,NaN,NaN,2.0,Marina,94123.0,"(37.79697456740493, -122.44615769723546)",147359384812
24,201708084249,8,otc alterations permit,08/08/2017,0542,039,1,NaN,Charlton,Ct,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.79739093461306, -122.43127133823367)",1473796372030
25,201708165014,8,otc alterations permit,08/16/2017,1824,006,1435,NaN,29th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,4.0,Sunset/Parkside,94122.0,"(37.76052279949518, -122.4879889739165)",1474841115935
26,M820728,8,otc alterations permit,08/18/2017,1449,006,331,NaN,17th,Av,...,NaN,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121.0,"(37.78177022745135, -122.47658979438802)",1475223100163
27,M821207,8,otc alterations permit,08/21/2017,1193,024,120,NaN,Shrader,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77371007080848, -122.45243180846707)",147537591942
28,M821268,8,otc alterations permit,08/21/2017,1851,012,1512,NaN,06th,Av,...,NaN,NaN,NaN,NaN,NaN,7.0,Inner Sunset,94122.0,"(37.760252335082875, -122.4625393396095)",1475405117215
29,M821847,8,otc alterations permit,08/22/2017,0326,001,165,NaN,Powell,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78625524960107, -122.40834431815433)",1475605447747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,M893328,8,otc alterations permit,02/23/2018,0025,024,888,NaN,North Point,St,...,NaN,NaN,NaN,NaN,NaN,2.0,Russian Hill,94109.0,"(37.8057495627139, -122.42181538597318)",1498327347381
198871,M893347,8,otc alterations permit,02/23/2018,1253,001,701,NaN,Clayton,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Haight Ashbury,94117.0,"(37.76869660680249, -122.44864582118123)",1498328241068
198872,201802232165,8,otc alterations permit,02/23/2018,3543,012,2123,NaN,Market,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Castro/Upper Market,94114.0,"(37.76682151637876, -122.42926240167795)",1498329423799
198873,201802232166,8,otc alterations permit,02/23/2018,5723,041,100,NaN,Tompkins,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Bernal Heights,94110.0,"(37.73708421334594, -122.4157759256698)",1498330475722
198874,201802232106,8,otc alterations permit,02/23/2018,6592,023,336,NaN,Duncan,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Noe Valley,94131.0,"(37.746231746880696, -122.4285179313817)",1498331399024
198875,201802232167,8,otc alterations permit,02/23/2018,0807,010,580,NaN,Hayes,St,...,NaN,NaN,1.0,constr type 1,NaN,5.0,Hayes Valley,94102.0,"(37.776756688343944, -122.4260292019233)",149833282001
198876,M893367,8,otc alterations permit,02/23/2018,1213,013,500,NaN,Stanyan,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77277103274044, -122.45392960440346)",149833392632
198877,201802232169,8,otc alterations permit,02/23/2018,7103,020,91,NaN,Lobos,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Oceanview/Merced/Ingleside,94112.0,"(37.7146765393289, -122.45557353560899)",1498334221586
198878,201802232170,8,otc alterations permit,02/23/2018,3641,016,3134,NaN,24th,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Mission,94110.0,"(37.752661001157854, -122.41485533400166)",1498335409431
198879,201802232171,8,otc alterations permit,02/23/2018,6082,009,350,NaN,Paris,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Excelsior,94112.0,"(37.72324934238285, -122.43409219261636)",1498336195616
198880,M893387,8,otc alterations permit,02/23/2018,1841,025D,1442,NaN,Funston,Av,...,NaN,NaN,NaN,NaN,NaN,7.0,Inner Sunset,94122.0,"(37.76117190796411, -122.47007880106999)",1498337116842
198881,M893407,8,otc alterations permit,02/23/2018,0018,004,2300,NaN,Stockton,St,...,NaN,NaN,NaN,NaN,NaN,3.0,North Beach,94133.0,"(37.80747140583783, -122.41024025753224)",1498338347099
198882,201802232172,8,otc alterations permit,02/23/2018,6021,001B,730,NaN,Excelsior,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Excelsior,94112.0,"(37.723206757170836, -122.42763728105176)",1498339194341
198883,M893427,8,otc alterations permit,02/23/2018,0315,021,377,NaN,Geary,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78696971667916, -122.40936701144197)",149834069380
198884,M893447,8,otc alterations permit,02/23/2018,3504,030,1699,NaN,Market,St,...,NaN,NaN,NaN,NaN,NaN,6.0,Mission,94103.0,"(37.77217130976155, -122.42193576313322)",1498341156230
198885,201802232173,8,otc alterations permit,02/23/2018,2150,001A,2007,NaN,30th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,4.0,Sunset/Parkside,94116.0,"(37.74976582284573, -122.48824447038214)",1498342127659
198886,201709066971,3,additions alterations or repairs,09/06/2017,0999,025,3191,NaN,Washington,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1477559238559
198887,201710040362,8,otc alterations permit,10/04/2017,0750,001,1521,NaN,Eddy,St,...,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN,1482126434174
198888,201710110995,8,otc alterations permit,10/11/2017,0726,019,1410,NaN,Steiner,St,...,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN,1483035367814
198889,201710242114,8,otc alterations permit,10/24/2017,1654,035,748,NaN,12th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1484587273155
198890,201711274822,3,additions alterations or repairs,11/27/2017,3803,001,185,NaN,Berry,St,...,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN,1488352388160
198891,201711274844,8,otc alterations permit,11/27/2017,0766,008,590,NaN,Van Ness,Av,...,3.0,constr type 3,3.0,constr type 3,NaN,NaN,NaN,NaN,NaN,148838081446
198892,201712045380,8,otc alterations permit,12/04/2017,1180,021,1543,NaN,Mcallister,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,148916691540
198893,201712055472,8,otc alterations permit,12/05/2017,1000,014,3018,NaN,Clay,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489281258414
198894,201712055493,8,otc alterations permit,12/05/2017,3522,006,340,NaN,12th,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489308256860
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,NaN,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,NaN,Sutter,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

In [54]:
df = sf_permits[['Current Status','Permit Type','Filed Date','Issued Date','Zipcode','Supervisor District']]

In [55]:
df

,Current Status,Permit Type,Filed Date,Issued Date,Zipcode,Supervisor District
0,expired,4,05/06/2015,11/09/2015,94102.0,3.0
1,issued,4,04/19/2016,08/03/2017,94102.0,3.0
2,withdrawn,3,05/27/2016,NaN,94109.0,3.0
3,complete,8,11/07/2016,07/18/2017,94109.0,3.0
4,issued,6,11/28/2016,12/01/2017,94102.0,6.0
5,issued,8,06/14/2017,07/06/2017,94107.0,10.0
6,complete,8,06/30/2017,06/30/2017,94122.0,5.0
7,issued,8,06/30/2017,06/30/2017,94124.0,10.0
8,issued,8,07/05/2017,07/05/2017,94117.0,5.0
9,issued,8,07/06/2017,07/06/2017,94117.0,8.0
10,issued,8,07/06/2017,07/06/2017,94114.0,8.0
11,issued,8,07/07/2017,07/07/2017,94102.0,5.0
12,issued,8,07/10/2017,07/10/2017,94114.0,8.0
13,filed,8,07/25/2017,NaN,94131.0,8.0
14,issued,8,07/26/2017,07/26/2017,94115.0,2.0
15,issued,8,07/27/2017,07/27/2017,94108.0,3.0
16,issued,8,07/27/2017,07/27/2017,94104.0,3.0
17,issued,8,07/27/2017,07/27/2017,94114.0,8.0
18,filed,8,07/28/2017,NaN,94123.0,2.0
19,issued,8,07/28/2017,07/28/2017,94114.0,8.0
20,issued,8,07/31/2017,07/31/2017,94117.0,5.0
21,filed,8,08/01/2017,NaN,94110.0,9.0
22,filed,3,08/01/2017,NaN,94133.0,3.0
23,issued,8,08/07/2017,08/07/2017,94123.0,2.0
24,issued,8,08/08/2017,08/08/2017,94123.0,2.0
25,issued,8,08/16/2017,08/16/2017,94122.0,4.0
26,issued,8,08/18/2017,08/18/2017,94121.0,1.0
27,issued,8,08/21/2017,08/21/2017,94117.0,5.0
28,issued,8,08/21/2017,08/21/2017,94122.0,7.0
29,issued,8,08/22/2017,08/22/2017,94102.0,3.0
...,...,...,...,...,...,...
198870,issued,8,02/23/2018,02/23/2018,94109.0,2.0
198871,issued,8,02/23/2018,02/23/2018,94117.0,5.0
198872,filed,8,02/23/2018,NaN,94114.0,8.0
198873,issued,8,02/23/2018,02/23/2018,94110.0,9.0
198874,issued,8,02/23/2018,02/23/2018,94131.0,8.0
198875,filed,8,02/23/2018,NaN,94102.0,5.0
198876,issued,8,02/23/2018,02/23/2018,94117.0,5.0
198877,issued,8,02/23/2018,02/23/2018,94112.0,11.0
198878,filed,8,02/23/2018,NaN,94110.0,9.0
198879,issued,8,02/23/2018,02/23/2018,94112.0,11.0
198880,issued,8,02/23/2018,02/23/2018,94122.0,7.0
198881,issued,8,02/23/2018,02/23/2018,94133.0,3.0
198882,issued,8,02/23/2018,02/23/2018,94112.0,11.0
198883,issued,8,02/23/2018,02/23/2018,94102.0,3.0
198884,filed,8,02/23/2018,NaN,94103.0,6.0
198885,filed,8,02/23/2018,NaN,94116.0,4.0
198886,approved,3,09/06/2017,NaN,NaN,NaN
198887,complete,8,10/04/2017,11/03/2017,NaN,NaN
198888,complete,8,10/11/2017,10/12/2017,NaN,NaN
198889,complete,8,10/24/2017,10/24/2017,NaN,NaN
198890,filed,3,11/27/2017,NaN,NaN,NaN
198891,issued,8,11/27/2017,12/08/2017,NaN,NaN
198892,issued,8,12/04/2017,01/16/2018,NaN,NaN
198893,complete,8,12/05/2017,12/05/2017,NaN,NaN
198894,issued,8,12/05/2017,12/05/2017,NaN,NaN
198895,issued,8,12/05/2017,12/05/2017,NaN,NaN
198896,issued,8,12/05/2017,12/06/2017,NaN,NaN
198897,issued,8,12/06/2017,12/06/2017,NaN,NaN
198898,issued,8,12/06/2017,12/06/2017,NaN,NaN
198899,issued,8,12/07/2017,12/07/2017,NaN,NaN

In [56]:
zips = pd.get_dummies( df['Zipcode'] , prefix = 'z' )

In [57]:
df=pd.concat([df, zips], axis=1)

In [58]:
pts = pd.get_dummies( df['Permit Type'] , prefix = 'pt' )

In [59]:
df=pd.concat([df, pts], axis=1)
sds = pd.get_dummies( df['Supervisor District'] , prefix = 'sd' )
df=pd.concat([df, sds], axis=1)

In [60]:
df=df.drop(columns=['Zipcode','Permit Type','Supervisor District'])

In [61]:
df

,Current Status,Filed Date,Issued Date,z_94102.0,z_94103.0,z_94104.0,z_94105.0,z_94107.0,z_94108.0,z_94109.0,...,sd_2.0,sd_3.0,sd_4.0,sd_5.0,sd_6.0,sd_7.0,sd_8.0,sd_9.0,sd_10.0,sd_11.0
0,expired,05/06/2015,11/09/2015,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,issued,04/19/2016,08/03/2017,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,withdrawn,05/27/2016,NaN,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
3,complete,11/07/2016,07/18/2017,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
4,issued,11/28/2016,12/01/2017,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,issued,06/14/2017,07/06/2017,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
6,complete,06/30/2017,06/30/2017,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
7,issued,06/30/2017,06/30/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8,issued,07/05/2017,07/05/2017,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,issued,07/06/2017,07/06/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
10,issued,07/06/2017,07/06/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
11,issued,07/07/2017,07/07/2017,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
12,issued,07/10/2017,07/10/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13,filed,07/25/2017,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,issued,07/26/2017,07/26/2017,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
15,issued,07/27/2017,07/27/2017,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
16,issued,07/27/2017,07/27/2017,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,issued,07/27/2017,07/27/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
18,filed,07/28/2017,NaN,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,issued,07/28/2017,07/28/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,issued,07/31/2017,07/31/2017,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
21,filed,08/01/2017,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
22,filed,08/01/2017,NaN,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
23,issued,08/07/2017,08/07/2017,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24,issued,08/08/2017,08/08/2017,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,issued,08/16/2017,08/16/2017,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
26,issued,08/18/2017,08/18/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,issued,08/21/2017,08/21/2017,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
28,issued,08/21/2017,08/21/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
29,issued,08/22/2017,08/22/2017,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
198871,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198872,filed,02/23/2018,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
198873,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
198874,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
198875,filed,02/23/2018,NaN,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198876,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198877,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198878,filed,02/23/2018,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
198879,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198880,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
198881,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
198882,issued,02/23/2018,02/23/2018,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198883,issued,02/23/2018,02/23/2018,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
198884,filed,02/23/2018,NaN,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
198885,filed,02/23/2018,NaN,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
198886,approved,09/06/2017,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198887,complete,10/04/2017,11/03/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198888,complete,10/11/2017,10/12/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198889,complete,10/24/2017,10/24/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198890,filed,11/27/2017,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198891,issued,11/27/2017,12/08/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198892,issued,12/04/2017,01/16/2018,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198893,complete,12/05/2017,12/05/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198894,issued,12/05/2017,12/05/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198895,issued,12/05/2017,12/05/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198896,issued,12/05/2017,12/06/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198897,issued,12/06/2017,12/06/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198898,issued,12/06/2017,12/06/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198899,issued,12/07/2017,12/07/2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:
df['from_date']=pd.to_datetime(df['Filed Date'])

In [63]:
df['to_date']=pd.to_datetime(df['Issued Date'])
df['process_time']=df['to_date']-df['from_date']
df['total_time']=df['process_time'].astype('timedelta64[D]')

In [64]:
df=df.drop(columns=['process_time'])

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 52 columns):
Current Status    198900 non-null object
Filed Date        198900 non-null object
Issued Date       183960 non-null object
z_94102.0         198900 non-null uint8
z_94103.0         198900 non-null uint8
z_94104.0         198900 non-null uint8
z_94105.0         198900 non-null uint8
z_94107.0         198900 non-null uint8
z_94108.0         198900 non-null uint8
z_94109.0         198900 non-null uint8
z_94110.0         198900 non-null uint8
z_94111.0         198900 non-null uint8
z_94112.0         198900 non-null uint8
z_94114.0         198900 non-null uint8
z_94115.0         198900 non-null uint8
z_94116.0         198900 non-null uint8
z_94117.0         198900 non-null uint8
z_94118.0         198900 non-null uint8
z_94121.0         198900 non-null uint8
z_94122.0         198900 non-null uint8
z_94123.0         198900 non-null uint8
z_94124.0         198900 non-null uint8
z_94127.0         198900 non-null uint8
z_94129.0         198900 non-null uint8
z_94130.0         198900 non-null uint8
z_94131.0         198900 non-null uint8
z_94132.0         198900 non-null uint8
z_94133.0         198900 non-null uint8
z_94134.0         198900 non-null uint8
z_94158.0         198900 non-null uint8
pt_1              198900 non-null uint8
pt_2              198900 non-null uint8
pt_3              198900 non-null uint8
pt_4              198900 non-null uint8
pt_5              198900 non-null uint8
pt_6              198900 non-null uint8
pt_7              198900 non-null uint8
pt_8              198900 non-null uint8
sd_1.0            198900 non-null uint8
sd_2.0            198900 non-null uint8
sd_3.0            198900 non-null uint8
sd_4.0            198900 non-null uint8
sd_5.0            198900 non-null uint8
sd_6.0            198900 non-null uint8
sd_7.0            198900 non-null uint8
sd_8.0            198900 non-null uint8
sd_9.0            198900 non-null uint8
sd_10.0           198900 non-null uint8
sd_11.0           198900 non-null uint8
from_date         198900 non-null datetime64[ns]
to_date           183960 non-null datetime64[ns]
total_time        183960 non-null float64
dtypes: datetime64[ns](2), float64(1), object(3), uint8(46)
memory usage: 17.8+ MB

In [68]:
df=df.drop(columns=['Filed Date','Issued Date'])

In [69]:
df

,Current Status,z_94102.0,z_94103.0,z_94104.0,z_94105.0,z_94107.0,z_94108.0,z_94109.0,z_94110.0,z_94111.0,...,sd_5.0,sd_6.0,sd_7.0,sd_8.0,sd_9.0,sd_10.0,sd_11.0,from_date,to_date,total_time
0,expired,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2015-05-06,2015-11-09,187.0
1,issued,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2016-04-19,2017-08-03,471.0
2,withdrawn,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,2016-05-27,NaT,NaN
3,complete,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,2016-11-07,2017-07-18,253.0
4,issued,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,2016-11-28,2017-12-01,368.0
5,issued,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,2017-06-14,2017-07-06,22.0
6,complete,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2017-06-30,2017-06-30,0.0
7,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,2017-06-30,2017-06-30,0.0
8,issued,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2017-07-05,2017-07-05,0.0
9,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2017-07-06,2017-07-06,0.0
10,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2017-07-06,2017-07-06,0.0
11,issued,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2017-07-07,2017-07-07,0.0
12,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2017-07-10,2017-07-10,0.0
13,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2017-07-25,NaT,NaN
14,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-07-26,2017-07-26,0.0
15,issued,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,2017-07-27,2017-07-27,0.0
16,issued,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-07-27,2017-07-27,0.0
17,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2017-07-27,2017-07-27,0.0
18,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-07-28,NaT,NaN
19,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2017-07-28,2017-07-28,0.0
20,issued,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2017-07-31,2017-07-31,0.0
21,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,2017-08-01,NaT,NaN
22,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-08-01,NaT,NaN
23,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-08-07,2017-08-07,0.0
24,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-08-08,2017-08-08,0.0
25,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-08-16,2017-08-16,0.0
26,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-08-18,2017-08-18,0.0
27,issued,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2017-08-21,2017-08-21,0.0
28,issued,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,2017-08-21,2017-08-21,0.0
29,issued,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-08-22,2017-08-22,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,issued,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,2018-02-23,2018-02-23,0.0
198871,issued,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2018-02-23,2018-02-23,0.0
198872,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2018-02-23,NaT,NaN
198873,issued,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,2018-02-23,2018-02-23,0.0
198874,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2018-02-23,2018-02-23,0.0
198875,filed,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2018-02-23,NaT,NaN
198876,issued,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2018-02-23,2018-02-23,0.0
198877,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,2018-02-23,2018-02-23,0.0
198878,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,2018-02-23,NaT,NaN
198879,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,2018-02-23,2018-02-23,0.0
198880,issued,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,2018-02-23,2018-02-23,0.0
198881,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2018-02-23,2018-02-23,0.0
198882,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,2018-02-23,2018-02-23,0.0
198883,issued,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2018-02-23,2018-02-23,0.0
198884,filed,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,2018-02-23,NaT,NaN
198885,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2018-02-23,NaT,NaN
198886,approved,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-09-06,NaT,NaN
198887,complete,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-10-04,2017-11-03,30.0
198888,complete,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-10-11,2017-10-12,1.0
198889,complete,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-10-24,2017-10-24,0.0
198890,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-11-27,NaT,NaN
198891,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-11-27,2017-12-08,11.0
198892,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-12-04,2018-01-16,43.0
198893,complete,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-12-05,2017-12-05,0.0
198894,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-12-05,2017-12-05,0.0
198895,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-12-05,2017-12-05,0.0
198896,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-12-05,2017-12-06,1.0
198897,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-12-06,2017-12-06,0.0
198898,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-12-06,2017-12-06,0.0
198899,issued,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-12-07,2017-12-07,0.0

In [70]:
import datetime as dt
df['from_date']=df['from_date'].map(dt.datetime.toordinal)
df['to_date']=df['to_date'].map(dt.datetime.toordinal)

In [119]:
df_filed = df.loc[df['Current Status'].isin(['filed'])]

In [72]:
df_completed = df.loc[df['Current Status'].isin(['complete','issued'])]

In [74]:
df_completed=df_completed.drop(columns=['Current Status'])
df_filed=df_filed.drop(columns=['Current Status'])

In [75]:
df_completed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180636 entries, 1 to 198899
Data columns (total 49 columns):
z_94102.0     180636 non-null uint8
z_94103.0     180636 non-null uint8
z_94104.0     180636 non-null uint8
z_94105.0     180636 non-null uint8
z_94107.0     180636 non-null uint8
z_94108.0     180636 non-null uint8
z_94109.0     180636 non-null uint8
z_94110.0     180636 non-null uint8
z_94111.0     180636 non-null uint8
z_94112.0     180636 non-null uint8
z_94114.0     180636 non-null uint8
z_94115.0     180636 non-null uint8
z_94116.0     180636 non-null uint8
z_94117.0     180636 non-null uint8
z_94118.0     180636 non-null uint8
z_94121.0     180636 non-null uint8
z_94122.0     180636 non-null uint8
z_94123.0     180636 non-null uint8
z_94124.0     180636 non-null uint8
z_94127.0     180636 non-null uint8
z_94129.0     180636 non-null uint8
z_94130.0     180636 non-null uint8
z_94131.0     180636 non-null uint8
z_94132.0     180636 non-null uint8
z_94133.0     180636 non-null uint8
z_94134.0     180636 non-null uint8
z_94158.0     180636 non-null uint8
pt_1          180636 non-null uint8
pt_2          180636 non-null uint8
pt_3          180636 non-null uint8
pt_4          180636 non-null uint8
pt_5          180636 non-null uint8
pt_6          180636 non-null uint8
pt_7          180636 non-null uint8
pt_8          180636 non-null uint8
sd_1.0        180636 non-null uint8
sd_2.0        180636 non-null uint8
sd_3.0        180636 non-null uint8
sd_4.0        180636 non-null uint8
sd_5.0        180636 non-null uint8
sd_6.0        180636 non-null uint8
sd_7.0        180636 non-null uint8
sd_8.0        180636 non-null uint8
sd_9.0        180636 non-null uint8
sd_10.0       180636 non-null uint8
sd_11.0       180636 non-null uint8
from_date     180636 non-null int64
to_date       180636 non-null int64
total_time    180618 non-null float64
dtypes: float64(1), int64(2), uint8(46)
memory usage: 13.4 MB

In [76]:
df_c2=df_completed.dropna()

In [77]:
df_c2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180618 entries, 1 to 198899
Data columns (total 49 columns):
z_94102.0     180618 non-null uint8
z_94103.0     180618 non-null uint8
z_94104.0     180618 non-null uint8
z_94105.0     180618 non-null uint8
z_94107.0     180618 non-null uint8
z_94108.0     180618 non-null uint8
z_94109.0     180618 non-null uint8
z_94110.0     180618 non-null uint8
z_94111.0     180618 non-null uint8
z_94112.0     180618 non-null uint8
z_94114.0     180618 non-null uint8
z_94115.0     180618 non-null uint8
z_94116.0     180618 non-null uint8
z_94117.0     180618 non-null uint8
z_94118.0     180618 non-null uint8
z_94121.0     180618 non-null uint8
z_94122.0     180618 non-null uint8
z_94123.0     180618 non-null uint8
z_94124.0     180618 non-null uint8
z_94127.0     180618 non-null uint8
z_94129.0     180618 non-null uint8
z_94130.0     180618 non-null uint8
z_94131.0     180618 non-null uint8
z_94132.0     180618 non-null uint8
z_94133.0     180618 non-null uint8
z_94134.0     180618 non-null uint8
z_94158.0     180618 non-null uint8
pt_1          180618 non-null uint8
pt_2          180618 non-null uint8
pt_3          180618 non-null uint8
pt_4          180618 non-null uint8
pt_5          180618 non-null uint8
pt_6          180618 non-null uint8
pt_7          180618 non-null uint8
pt_8          180618 non-null uint8
sd_1.0        180618 non-null uint8
sd_2.0        180618 non-null uint8
sd_3.0        180618 non-null uint8
sd_4.0        180618 non-null uint8
sd_5.0        180618 non-null uint8
sd_6.0        180618 non-null uint8
sd_7.0        180618 non-null uint8
sd_8.0        180618 non-null uint8
sd_9.0        180618 non-null uint8
sd_10.0       180618 non-null uint8
sd_11.0       180618 non-null uint8
from_date     180618 non-null int64
to_date       180618 non-null int64
total_time    180618 non-null float64
dtypes: float64(1), int64(2), uint8(46)
memory usage: 13.4 MB

In [78]:
# ML Algorithm
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [123]:
reg=linear_model.LinearRegression()

In [124]:
df_x=df_c2.drop(columns=['total_time','to_date'])
df_y=df_c2['total_time']

In [125]:
df_x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180618 entries, 1 to 198899
Data columns (total 47 columns):
z_94102.0    180618 non-null uint8
z_94103.0    180618 non-null uint8
z_94104.0    180618 non-null uint8
z_94105.0    180618 non-null uint8
z_94107.0    180618 non-null uint8
z_94108.0    180618 non-null uint8
z_94109.0    180618 non-null uint8
z_94110.0    180618 non-null uint8
z_94111.0    180618 non-null uint8
z_94112.0    180618 non-null uint8
z_94114.0    180618 non-null uint8
z_94115.0    180618 non-null uint8
z_94116.0    180618 non-null uint8
z_94117.0    180618 non-null uint8
z_94118.0    180618 non-null uint8
z_94121.0    180618 non-null uint8
z_94122.0    180618 non-null uint8
z_94123.0    180618 non-null uint8
z_94124.0    180618 non-null uint8
z_94127.0    180618 non-null uint8
z_94129.0    180618 non-null uint8
z_94130.0    180618 non-null uint8
z_94131.0    180618 non-null uint8
z_94132.0    180618 non-null uint8
z_94133.0    180618 non-null uint8
z_94134.0    180618 non-null uint8
z_94158.0    180618 non-null uint8
pt_1         180618 non-null uint8
pt_2         180618 non-null uint8
pt_3         180618 non-null uint8
pt_4         180618 non-null uint8
pt_5         180618 non-null uint8
pt_6         180618 non-null uint8
pt_7         180618 non-null uint8
pt_8         180618 non-null uint8
sd_1.0       180618 non-null uint8
sd_2.0       180618 non-null uint8
sd_3.0       180618 non-null uint8
sd_4.0       180618 non-null uint8
sd_5.0       180618 non-null uint8
sd_6.0       180618 non-null uint8
sd_7.0       180618 non-null uint8
sd_8.0       180618 non-null uint8
sd_9.0       180618 non-null uint8
sd_10.0      180618 non-null uint8
sd_11.0      180618 non-null uint8
from_date    180618 non-null int64
dtypes: int64(1), uint8(46)
memory usage: 15.7 MB

In [126]:
#x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size=0.3,random_state=4)
x_train=df_x[:130618]
x_test=df_x[130618:]
y_train=df_y[:130618]
y_test=df_y[130618:]

In [127]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 130618 entries, 1 to 140293
Data columns (total 47 columns):
z_94102.0    130618 non-null uint8
z_94103.0    130618 non-null uint8
z_94104.0    130618 non-null uint8
z_94105.0    130618 non-null uint8
z_94107.0    130618 non-null uint8
z_94108.0    130618 non-null uint8
z_94109.0    130618 non-null uint8
z_94110.0    130618 non-null uint8
z_94111.0    130618 non-null uint8
z_94112.0    130618 non-null uint8
z_94114.0    130618 non-null uint8
z_94115.0    130618 non-null uint8
z_94116.0    130618 non-null uint8
z_94117.0    130618 non-null uint8
z_94118.0    130618 non-null uint8
z_94121.0    130618 non-null uint8
z_94122.0    130618 non-null uint8
z_94123.0    130618 non-null uint8
z_94124.0    130618 non-null uint8
z_94127.0    130618 non-null uint8
z_94129.0    130618 non-null uint8
z_94130.0    130618 non-null uint8
z_94131.0    130618 non-null uint8
z_94132.0    130618 non-null uint8
z_94133.0    130618 non-null uint8
z_94134.0    130618 non-null uint8
z_94158.0    130618 non-null uint8
pt_1         130618 non-null uint8
pt_2         130618 non-null uint8
pt_3         130618 non-null uint8
pt_4         130618 non-null uint8
pt_5         130618 non-null uint8
pt_6         130618 non-null uint8
pt_7         130618 non-null uint8
pt_8         130618 non-null uint8
sd_1.0       130618 non-null uint8
sd_2.0       130618 non-null uint8
sd_3.0       130618 non-null uint8
sd_4.0       130618 non-null uint8
sd_5.0       130618 non-null uint8
sd_6.0       130618 non-null uint8
sd_7.0       130618 non-null uint8
sd_8.0       130618 non-null uint8
sd_9.0       130618 non-null uint8
sd_10.0      130618 non-null uint8
sd_11.0      130618 non-null uint8
from_date    130618 non-null int64
dtypes: int64(1), uint8(46)
memory usage: 7.7 MB

In [128]:
model = reg.fit(x_train,y_train)

In [129]:
reg.coef_

array([  2.60327080e+01,   2.10971233e+01,   1.85847748e+01,
         2.26595837e+01,   2.19471966e+01,   2.32576322e+01,
         2.12411503e+01,   1.74833886e+01,   1.84430026e+01,
         1.39817619e+01,   2.02255404e+01,   2.25725727e+01,
         2.00873704e+01,   2.30268518e+01,   2.38273034e+01,
         2.55823524e+01,   2.02853805e+01,   2.44412473e+01,
         7.56874218e+00,   2.02262273e+01,   9.36406981e+00,
         2.53454800e+01,   2.22228859e+01,  -4.31780063e-01,
         1.83928645e+01,   1.39916097e+01,   7.47588477e+00,
         2.24347853e+02,   1.72017406e+02,   3.66864418e+01,
        -1.43296019e+02,  -9.18952337e+01,   1.35698825e+02,
        -1.45919143e+02,  -1.87640130e+02,  -1.73881496e+01,
        -1.82214106e+01,  -1.41556180e+01,  -1.36533382e+01,
        -1.68326913e+01,  -1.88207274e+01,  -1.49509638e+01,
        -1.29631231e+01,  -1.01671103e+01,  -9.16032580e+00,
        -3.67443584e+00,   9.19030392e-04])

In [130]:
a=reg.predict(x_test)

In [131]:
model.score(x_test,y_test)

0.39202478460835555

In [132]:
from sklearn.metrics import mean_squared_error

In [133]:
mean_squared_error(y_test,a)

5852.382596829777

In [113]:
a

array([  4.48423521e-11,   1.40000000e+01,   4.48423521e-11, ...,
         4.48423521e-11,   4.48423521e-11,   4.48423521e-11])

In [114]:
pd.DataFrame(a)

                  0
0      4.484235e-11
1      1.400000e+01
2      4.484235e-11
3      4.484235e-11
4      4.000000e+00
5      4.000000e+00
6      4.484235e-11
7      1.100000e+01
8      4.484235e-11
9      4.484235e-11
10     4.484235e-11
11     4.484235e-11
12     4.484235e-11
13     1.000000e+00
14     4.484235e-11
15     4.484235e-11
16     4.484235e-11
17     2.100000e+01
18     2.100000e+01
19     4.484235e-11
20     8.000000e+00
21     4.484235e-11
22     1.820000e+02
23     4.484235e-11
24     4.484235e-11
25     4.484235e-11
26     6.000000e+00
27     4.484235e-11
28     4.484235e-11
29     4.484235e-11
...             ...
49970  4.484235e-11
49971  4.484235e-11
49972  4.484235e-11
49973  4.484235e-11
49974  4.484235e-11
49975  4.484235e-11
49976  4.484235e-11
49977  4.484235e-11
49978  4.484235e-11
49979  4.484235e-11
49980  4.484235e-11
49981  4.484235e-11
49982  4.484235e-11
49983  4.484235e-11
49984  4.484235e-11
49985  4.484235e-11
49986  4.484235e-11
49987  4.484235e-11
49988  3.000000e+01
49989  1.000000e+00
49990  4.484235e-11
49991  1.100000e+01
49992  4.300000e+01
49993  4.484235e-11
49994  4.484235e-11
49995  4.484235e-11
49996  1.000000e+00
49997  4.484235e-11
49998  4.484235e-11
49999  4.484235e-11

[50000 rows x 1 columns]

In [115]:
y_test

140294      0.0
140295     14.0
140296      0.0
140297      0.0
140300      4.0
140302      4.0
140304      0.0
140305     11.0
140306      0.0
140307      0.0
140308      0.0
140309      0.0
140310      0.0
140311      1.0
140312      0.0
140313      0.0
140314      0.0
140315     21.0
140316     21.0
140317      0.0
140318      8.0
140319      0.0
140320    182.0
140321      0.0
140322      0.0
140323      0.0
140324      6.0
140325      0.0
140327      0.0
140328      0.0
          ...
198858      0.0
198861      0.0
198863      0.0
198865      0.0
198867      0.0
198868      0.0
198869      0.0
198870      0.0
198871      0.0
198873      0.0
198874      0.0
198876      0.0
198877      0.0
198879      0.0
198880      0.0
198881      0.0
198882      0.0
198883      0.0
198887     30.0
198888      1.0
198889      0.0
198891     11.0
198892     43.0
198893      0.0
198894      0.0
198895      0.0
198896      1.0
198897      0.0
198898      0.0
198899      0.0
Name: total_time, Length: 50000, dtype: float64

In [122]:
df_filed

,Current Status,z_94102.0,z_94103.0,z_94104.0,z_94105.0,z_94107.0,z_94108.0,z_94109.0,z_94110.0,z_94111.0,...,sd_5.0,sd_6.0,sd_7.0,sd_8.0,sd_9.0,sd_10.0,sd_11.0,from_date,to_date,total_time
13,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,736535,1,NaN
18,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736538,1,NaN
21,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,736542,1,NaN
22,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736542,1,NaN
42,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736587,1,NaN
55,filed,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,736626,1,NaN
64,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,736648,1,NaN
82,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,736682,1,NaN
83,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,736683,1,NaN
89,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736691,1,NaN
149,filed,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,736516,1,NaN
164,filed,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,736524,1,NaN
165,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,736524,1,NaN
176,filed,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,736534,1,NaN
194,filed,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,736544,1,NaN
233,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736565,1,NaN
236,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,736566,1,NaN
245,filed,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,736570,1,NaN
247,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,736571,1,NaN
253,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736571,1,NaN
256,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,736573,1,NaN
265,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736578,1,NaN
268,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,736579,1,NaN
280,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736585,1,NaN
282,filed,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,736584,1,NaN
283,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736585,1,NaN
286,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,736586,1,NaN
289,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736587,1,NaN
291,filed,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,736587,1,NaN
293,filed,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,736587,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198818,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198819,filed,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,736748,1,NaN
198820,filed,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,736748,1,NaN
198823,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198826,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,736748,1,NaN
198827,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198828,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198829,filed,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,736748,1,NaN
198832,filed,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,736748,1,NaN
198836,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198838,filed,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198839,filed,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198848,filed,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,736748,1,NaN
198849,filed,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198853,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,736748,1,NaN
198854,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,736748,1,NaN
198855,filed,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,736748,1,NaN
198856,filed,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198857,filed,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,736748,1,NaN
198859,filed,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,736748,1,NaN
198860,filed,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,736748,1,NaN
198862,filed,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198864,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,736748,1,NaN
198866,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198872,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,736748,1,NaN
198875,filed,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,736748,1,NaN
198878,filed,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,736748,1,NaN
198884,filed,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,736748,1,NaN
198885,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736748,1,NaN
198890,filed,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,736660,1,NaN