In [1]:
import pandas as pd
import numpy as np

In [2]:
sf_permits = pd.read_csv("../dataset/building-permit-applications-data/Building_Permits.csv")

/home/neil/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
sf_pemits2 = sf_permits.drop(columns=['Permit Number','Permit Type Definition','Block','Lot','Street Number','Street Number Suffix','Street Name','Street Suffix','Unit','Unit Suffix','Description','Structural Notification','Number of Existing Stories','Number of Proposed Stories','Voluntary Soft-Story Retrofit','Fire Only Permit','Existing Use','Existing Units','Proposed Use','Proposed Units','Plansets','TIDF Compliance','Existing Construction Type','Existing Construction Type Description','Proposed Construction Type','Proposed Construction Type Description','Site Permit','Neighborhoods - Analysis Boundaries','Location','Record ID'])

In [6]:
#df2 = sf_pemits2.loc[sf_pemits2['Current Status'].isin(['issued','complete'])]
df2=sf_pemits2

In [7]:
#df2['Current Status']

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 13 columns):
Permit Type                         198900 non-null int64
Permit Creation Date                198900 non-null object
Current Status                      198900 non-null object
Current Status Date                 198900 non-null object
Filed Date                          198900 non-null object
Issued Date                         183960 non-null object
Completed Date                      97191 non-null object
First Construction Document Date    183954 non-null object
Permit Expiration Date              147020 non-null object
Estimated Cost                      160834 non-null float64
Revised Cost                        192834 non-null float64
Supervisor District                 197183 non-null float64
Zipcode                             197184 non-null float64
dtypes: float64(4), int64(1), object(8)
memory usage: 19.7+ MB

In [9]:
missing = df2.isnull().sum()

In [10]:
missing

Permit Type                              0
Permit Creation Date                     0
Current Status                           0
Current Status Date                      0
Filed Date                               0
Issued Date                          14940
Completed Date                      101709
First Construction Document Date     14946
Permit Expiration Date               51880
Estimated Cost                       38066
Revised Cost                          6066
Supervisor District                   1717
Zipcode                               1716
dtype: int64

In [11]:
df3 = df2.drop(columns=['Completed Date','Permit Expiration Date','Estimated Cost','Permit Creation Date','Current Status Date'])

In [12]:
missing2 = df3.isnull().sum()

In [13]:
missing2

Permit Type                             0
Current Status                          0
Filed Date                              0
Issued Date                         14940
First Construction Document Date    14946
Revised Cost                         6066
Supervisor District                  1717
Zipcode                              1716
dtype: int64

In [14]:
#df4 = df3[pd.notnull(df3['Issued Date'])]
df4=df3

In [15]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 8 columns):
Permit Type                         198900 non-null int64
Current Status                      198900 non-null object
Filed Date                          198900 non-null object
Issued Date                         183960 non-null object
First Construction Document Date    183954 non-null object
Revised Cost                        192834 non-null float64
Supervisor District                 197183 non-null float64
Zipcode                             197184 non-null float64
dtypes: float64(3), int64(1), object(4)
memory usage: 12.1+ MB

In [16]:
#import datetime as dt
#df4['Permit Creation Date'] = pd.to_datetime(df4['Permit Creation Date'])
#df4['Permit Creation Date66']=df4['Permit Creation Date'].map(dt.datetime.toordinal)

In [17]:
#df4['Permit Creation Date66']

In [18]:
#status = pd.Series(np.where(df4['Current Status']=='issued',1,0),name='Current Status')

In [19]:
#status

In [20]:
#import datetime as dt
#df4['Current Status Date'] = pd.to_datetime(df4['Current Status Date'])
#df4['Current Status Date66']=df4['Current Status Date'].map(dt.datetime.toordinal)

In [21]:
#df4['Current Status Date66']

In [22]:
#df4['Filed Date'] = pd.to_datetime(df4['Filed Date'])
#df4['Filed Date66']=df4['Filed Date'].map(dt.datetime.toordinal)

In [23]:
#df4['Filed Date66']

In [24]:
#df4['Issued Date'] = pd.to_datetime(df4['Issued Date'])
#df4['Issued Date66']=df4['Issued Date'].map(dt.datetime.toordinal)

In [25]:
#df4['Issued Date66']

In [26]:
df5 = df4

In [27]:
df5

,Permit Type,Current Status,Filed Date,Issued Date,First Construction Document Date,Revised Cost,Supervisor District,Zipcode
0,4,expired,05/06/2015,11/09/2015,11/09/2015,4000.00,3.0,94102.0
1,4,issued,04/19/2016,08/03/2017,08/03/2017,500.00,3.0,94102.0
2,3,withdrawn,05/27/2016,NaN,NaN,NaN,3.0,94109.0
3,8,complete,11/07/2016,07/18/2017,07/18/2017,2000.00,3.0,94109.0
4,6,issued,11/28/2016,12/01/2017,11/20/2017,100000.00,6.0,94102.0
5,8,issued,06/14/2017,07/06/2017,07/06/2017,4000.00,10.0,94107.0
6,8,complete,06/30/2017,06/30/2017,06/30/2017,12000.00,5.0,94122.0
7,8,issued,06/30/2017,06/30/2017,06/30/2017,0.00,10.0,94124.0
8,8,issued,07/05/2017,07/05/2017,07/05/2017,1.00,5.0,94117.0
9,8,issued,07/06/2017,07/06/2017,07/06/2017,0.00,8.0,94117.0
10,8,issued,07/06/2017,07/06/2017,07/06/2017,1.00,8.0,94114.0
11,8,issued,07/07/2017,07/07/2017,07/07/2017,1.00,5.0,94102.0
12,8,issued,07/10/2017,07/10/2017,07/10/2017,1.00,8.0,94114.0
13,8,filed,07/25/2017,NaN,NaN,0.00,8.0,94131.0
14,8,issued,07/26/2017,07/26/2017,07/26/2017,1.00,2.0,94115.0
15,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,94108.0
16,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,94104.0
17,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,8.0,94114.0
18,8,filed,07/28/2017,NaN,NaN,0.00,2.0,94123.0
19,8,issued,07/28/2017,07/28/2017,07/28/2017,1.00,8.0,94114.0
20,8,issued,07/31/2017,07/31/2017,07/31/2017,1.00,5.0,94117.0
21,8,filed,08/01/2017,NaN,NaN,0.00,9.0,94110.0
22,3,filed,08/01/2017,NaN,NaN,NaN,3.0,94133.0
23,8,issued,08/07/2017,08/07/2017,08/07/2017,1.00,2.0,94123.0
24,8,issued,08/08/2017,08/08/2017,08/08/2017,64650.00,2.0,94123.0
25,8,issued,08/16/2017,08/16/2017,08/16/2017,7000.00,4.0,94122.0
26,8,issued,08/18/2017,08/18/2017,08/18/2017,1.00,1.0,94121.0
27,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,5.0,94117.0
28,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,7.0,94122.0
29,8,issued,08/22/2017,08/22/2017,08/22/2017,1.00,3.0,94102.0
...,...,...,...,...,...,...,...,...
198870,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94109.0
198871,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,5.0,94117.0
198872,8,filed,02/23/2018,NaN,NaN,0.00,8.0,94114.0
198873,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,9.0,94110.0
198874,8,issued,02/23/2018,02/23/2018,02/23/2018,15000.00,8.0,94131.0
198875,8,filed,02/23/2018,NaN,NaN,0.00,5.0,94102.0
198876,8,issued,02/23/2018,02/23/2018,02/23/2018,0.00,5.0,94117.0
198877,8,issued,02/23/2018,02/23/2018,02/23/2018,1000.00,11.0,94112.0
198878,8,filed,02/23/2018,NaN,NaN,0.00,9.0,94110.0
198879,8,issued,02/23/2018,02/23/2018,02/23/2018,18453.12,11.0,94112.0
198880,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,7.0,94122.0
198881,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94133.0
198882,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,11.0,94112.0
198883,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94102.0
198884,8,filed,02/23/2018,NaN,NaN,1.00,6.0,94103.0
198885,8,filed,02/23/2018,NaN,NaN,0.00,4.0,94116.0
198886,3,approved,09/06/2017,NaN,NaN,65000.00,NaN,NaN
198887,8,complete,10/04/2017,11/03/2017,11/03/2017,30000.00,NaN,NaN
198888,8,complete,10/11/2017,10/12/2017,10/12/2017,30000.00,NaN,NaN
198889,8,complete,10/24/2017,10/24/2017,10/24/2017,20000.00,NaN,NaN
198890,3,filed,11/27/2017,NaN,NaN,750000.00,NaN,NaN
198891,8,issued,11/27/2017,12/08/2017,12/08/2017,1.00,NaN,NaN
198892,8,issued,12/04/2017,01/16/2018,01/16/2018,38000.00,NaN,NaN
198893,8,complete,12/05/2017,12/05/2017,12/05/2017,2800.00,NaN,NaN
198894,8,issued,12/05/2017,12/05/2017,12/05/2017,7400.00,NaN,NaN
198895,8,issued,12/05/2017,12/05/2017,12/05/2017,1.00,NaN,NaN
198896,8,issued,12/05/2017,12/06/2017,12/06/2017,5000.00,NaN,NaN
198897,8,issued,12/06/2017,12/06/2017,12/06/2017,1.00,NaN,NaN
198898,8,issued,12/06/2017,12/06/2017,12/06/2017,1.00,NaN,NaN
198899,8,issued,12/07/2017,12/07/2017,12/07/2017,1.00,NaN,NaN

In [28]:
#df5 = df5.drop(columns=['Current Status','First Construction Document Date','Permit Creation Date','Current Status Date','Filed Date','Issued Date'])

In [29]:
#df5

In [30]:
#df6=pd.concat([df5, status], axis=1)
df6=df5

In [31]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 8 columns):
Permit Type                         198900 non-null int64
Current Status                      198900 non-null object
Filed Date                          198900 non-null object
Issued Date                         183960 non-null object
First Construction Document Date    183954 non-null object
Revised Cost                        192834 non-null float64
Supervisor District                 197183 non-null float64
Zipcode                             197184 non-null float64
dtypes: float64(3), int64(1), object(4)
memory usage: 12.1+ MB

In [32]:
df6['Current Status'].unique()

array(['expired', 'issued', 'withdrawn', 'complete', 'filed', 'approved',
       'reinstated', 'cancelled', 'appeal', 'suspend', 'revoked',
       'plancheck', 'disapproved', 'incomplete'], dtype=object)

In [33]:
# remove null rows
df7 = df6[pd.notnull(df6['Zipcode'])]

In [34]:
df7

,Permit Type,Current Status,Filed Date,Issued Date,First Construction Document Date,Revised Cost,Supervisor District,Zipcode
0,4,expired,05/06/2015,11/09/2015,11/09/2015,4000.00,3.0,94102.0
1,4,issued,04/19/2016,08/03/2017,08/03/2017,500.00,3.0,94102.0
2,3,withdrawn,05/27/2016,NaN,NaN,NaN,3.0,94109.0
3,8,complete,11/07/2016,07/18/2017,07/18/2017,2000.00,3.0,94109.0
4,6,issued,11/28/2016,12/01/2017,11/20/2017,100000.00,6.0,94102.0
5,8,issued,06/14/2017,07/06/2017,07/06/2017,4000.00,10.0,94107.0
6,8,complete,06/30/2017,06/30/2017,06/30/2017,12000.00,5.0,94122.0
7,8,issued,06/30/2017,06/30/2017,06/30/2017,0.00,10.0,94124.0
8,8,issued,07/05/2017,07/05/2017,07/05/2017,1.00,5.0,94117.0
9,8,issued,07/06/2017,07/06/2017,07/06/2017,0.00,8.0,94117.0
10,8,issued,07/06/2017,07/06/2017,07/06/2017,1.00,8.0,94114.0
11,8,issued,07/07/2017,07/07/2017,07/07/2017,1.00,5.0,94102.0
12,8,issued,07/10/2017,07/10/2017,07/10/2017,1.00,8.0,94114.0
13,8,filed,07/25/2017,NaN,NaN,0.00,8.0,94131.0
14,8,issued,07/26/2017,07/26/2017,07/26/2017,1.00,2.0,94115.0
15,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,94108.0
16,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,94104.0
17,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,8.0,94114.0
18,8,filed,07/28/2017,NaN,NaN,0.00,2.0,94123.0
19,8,issued,07/28/2017,07/28/2017,07/28/2017,1.00,8.0,94114.0
20,8,issued,07/31/2017,07/31/2017,07/31/2017,1.00,5.0,94117.0
21,8,filed,08/01/2017,NaN,NaN,0.00,9.0,94110.0
22,3,filed,08/01/2017,NaN,NaN,NaN,3.0,94133.0
23,8,issued,08/07/2017,08/07/2017,08/07/2017,1.00,2.0,94123.0
24,8,issued,08/08/2017,08/08/2017,08/08/2017,64650.00,2.0,94123.0
25,8,issued,08/16/2017,08/16/2017,08/16/2017,7000.00,4.0,94122.0
26,8,issued,08/18/2017,08/18/2017,08/18/2017,1.00,1.0,94121.0
27,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,5.0,94117.0
28,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,7.0,94122.0
29,8,issued,08/22/2017,08/22/2017,08/22/2017,1.00,3.0,94102.0
...,...,...,...,...,...,...,...,...
198856,8,filed,02/23/2018,NaN,NaN,0.00,3.0,94104.0
198857,8,filed,02/23/2018,NaN,NaN,0.00,6.0,94105.0
198858,8,issued,02/23/2018,02/23/2018,02/23/2018,0.00,2.0,94115.0
198859,8,filed,02/23/2018,NaN,NaN,0.00,6.0,94103.0
198860,8,filed,02/23/2018,NaN,NaN,0.00,10.0,94107.0
198861,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94108.0
198862,8,filed,02/23/2018,NaN,NaN,NaN,3.0,94109.0
198863,8,issued,02/23/2018,02/23/2018,02/23/2018,45000.00,5.0,94117.0
198864,8,filed,02/23/2018,NaN,NaN,0.00,9.0,94110.0
198865,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94118.0
198866,8,filed,02/23/2018,NaN,NaN,1.00,4.0,94116.0
198867,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,10.0,94107.0
198868,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,9.0,94110.0
198869,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94109.0
198870,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94109.0
198871,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,5.0,94117.0
198872,8,filed,02/23/2018,NaN,NaN,0.00,8.0,94114.0
198873,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,9.0,94110.0
198874,8,issued,02/23/2018,02/23/2018,02/23/2018,15000.00,8.0,94131.0
198875,8,filed,02/23/2018,NaN,NaN,0.00,5.0,94102.0
198876,8,issued,02/23/2018,02/23/2018,02/23/2018,0.00,5.0,94117.0
198877,8,issued,02/23/2018,02/23/2018,02/23/2018,1000.00,11.0,94112.0
198878,8,filed,02/23/2018,NaN,NaN,0.00,9.0,94110.0
198879,8,issued,02/23/2018,02/23/2018,02/23/2018,18453.12,11.0,94112.0
198880,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,7.0,94122.0
198881,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94133.0
198882,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,11.0,94112.0
198883,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94102.0
198884,8,filed,02/23/2018,NaN,NaN,1.00,6.0,94103.0
198885,8,filed,02/23/2018,NaN,NaN,0.00,4.0,94116.0

In [35]:
df7['Current Status'].unique()

array(['expired', 'issued', 'withdrawn', 'complete', 'filed', 'approved',
       'reinstated', 'cancelled', 'appeal', 'suspend', 'revoked',
       'plancheck', 'disapproved', 'incomplete'], dtype=object)

In [37]:
#df8 = df7.dropna()
df8=df7

In [38]:
df8

,Permit Type,Current Status,Filed Date,Issued Date,First Construction Document Date,Revised Cost,Supervisor District,Zipcode
0,4,expired,05/06/2015,11/09/2015,11/09/2015,4000.00,3.0,94102.0
1,4,issued,04/19/2016,08/03/2017,08/03/2017,500.00,3.0,94102.0
2,3,withdrawn,05/27/2016,NaN,NaN,NaN,3.0,94109.0
3,8,complete,11/07/2016,07/18/2017,07/18/2017,2000.00,3.0,94109.0
4,6,issued,11/28/2016,12/01/2017,11/20/2017,100000.00,6.0,94102.0
5,8,issued,06/14/2017,07/06/2017,07/06/2017,4000.00,10.0,94107.0
6,8,complete,06/30/2017,06/30/2017,06/30/2017,12000.00,5.0,94122.0
7,8,issued,06/30/2017,06/30/2017,06/30/2017,0.00,10.0,94124.0
8,8,issued,07/05/2017,07/05/2017,07/05/2017,1.00,5.0,94117.0
9,8,issued,07/06/2017,07/06/2017,07/06/2017,0.00,8.0,94117.0
10,8,issued,07/06/2017,07/06/2017,07/06/2017,1.00,8.0,94114.0
11,8,issued,07/07/2017,07/07/2017,07/07/2017,1.00,5.0,94102.0
12,8,issued,07/10/2017,07/10/2017,07/10/2017,1.00,8.0,94114.0
13,8,filed,07/25/2017,NaN,NaN,0.00,8.0,94131.0
14,8,issued,07/26/2017,07/26/2017,07/26/2017,1.00,2.0,94115.0
15,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,94108.0
16,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,94104.0
17,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,8.0,94114.0
18,8,filed,07/28/2017,NaN,NaN,0.00,2.0,94123.0
19,8,issued,07/28/2017,07/28/2017,07/28/2017,1.00,8.0,94114.0
20,8,issued,07/31/2017,07/31/2017,07/31/2017,1.00,5.0,94117.0
21,8,filed,08/01/2017,NaN,NaN,0.00,9.0,94110.0
22,3,filed,08/01/2017,NaN,NaN,NaN,3.0,94133.0
23,8,issued,08/07/2017,08/07/2017,08/07/2017,1.00,2.0,94123.0
24,8,issued,08/08/2017,08/08/2017,08/08/2017,64650.00,2.0,94123.0
25,8,issued,08/16/2017,08/16/2017,08/16/2017,7000.00,4.0,94122.0
26,8,issued,08/18/2017,08/18/2017,08/18/2017,1.00,1.0,94121.0
27,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,5.0,94117.0
28,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,7.0,94122.0
29,8,issued,08/22/2017,08/22/2017,08/22/2017,1.00,3.0,94102.0
...,...,...,...,...,...,...,...,...
198856,8,filed,02/23/2018,NaN,NaN,0.00,3.0,94104.0
198857,8,filed,02/23/2018,NaN,NaN,0.00,6.0,94105.0
198858,8,issued,02/23/2018,02/23/2018,02/23/2018,0.00,2.0,94115.0
198859,8,filed,02/23/2018,NaN,NaN,0.00,6.0,94103.0
198860,8,filed,02/23/2018,NaN,NaN,0.00,10.0,94107.0
198861,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94108.0
198862,8,filed,02/23/2018,NaN,NaN,NaN,3.0,94109.0
198863,8,issued,02/23/2018,02/23/2018,02/23/2018,45000.00,5.0,94117.0
198864,8,filed,02/23/2018,NaN,NaN,0.00,9.0,94110.0
198865,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94118.0
198866,8,filed,02/23/2018,NaN,NaN,1.00,4.0,94116.0
198867,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,10.0,94107.0
198868,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,9.0,94110.0
198869,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94109.0
198870,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94109.0
198871,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,5.0,94117.0
198872,8,filed,02/23/2018,NaN,NaN,0.00,8.0,94114.0
198873,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,9.0,94110.0
198874,8,issued,02/23/2018,02/23/2018,02/23/2018,15000.00,8.0,94131.0
198875,8,filed,02/23/2018,NaN,NaN,0.00,5.0,94102.0
198876,8,issued,02/23/2018,02/23/2018,02/23/2018,0.00,5.0,94117.0
198877,8,issued,02/23/2018,02/23/2018,02/23/2018,1000.00,11.0,94112.0
198878,8,filed,02/23/2018,NaN,NaN,0.00,9.0,94110.0
198879,8,issued,02/23/2018,02/23/2018,02/23/2018,18453.12,11.0,94112.0
198880,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,7.0,94122.0
198881,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94133.0
198882,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,11.0,94112.0
198883,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94102.0
198884,8,filed,02/23/2018,NaN,NaN,1.00,6.0,94103.0
198885,8,filed,02/23/2018,NaN,NaN,0.00,4.0,94116.0

In [39]:
#df7 = df7[pd.notnull(df7['Current Status'])]

In [40]:
#df7 = df7[pd.notnull(df7['Revised Cost'])]

In [41]:
#df7 = df7[pd.notnull(df7['Supervisor District'])]

In [42]:
#df7.info()

In [43]:
zips = pd.get_dummies( df8['Zipcode'] , prefix = 'z' )

In [44]:
zips

,z_94102.0,z_94103.0,z_94104.0,z_94105.0,z_94107.0,z_94108.0,z_94109.0,z_94110.0,z_94111.0,z_94112.0,...,z_94123.0,z_94124.0,z_94127.0,z_94129.0,z_94130.0,z_94131.0,z_94132.0,z_94133.0,z_94134.0,z_94158.0
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198856,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198857,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198858,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198859,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198860,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198861,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198862,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198863,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198864,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
198865,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198866,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198867,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198868,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
198869,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198870,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198871,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198872,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198873,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
198874,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
198875,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198876,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198877,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
198878,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
198879,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
198880,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198881,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
198882,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
198883,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198884,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198885,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [45]:
df8=pd.concat([df8, zips], axis=1)

In [46]:
df8

,Permit Type,Current Status,Filed Date,Issued Date,First Construction Document Date,Revised Cost,Supervisor District,Zipcode,z_94102.0,z_94103.0,...,z_94123.0,z_94124.0,z_94127.0,z_94129.0,z_94130.0,z_94131.0,z_94132.0,z_94133.0,z_94134.0,z_94158.0
0,4,expired,05/06/2015,11/09/2015,11/09/2015,4000.00,3.0,94102.0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,4,issued,04/19/2016,08/03/2017,08/03/2017,500.00,3.0,94102.0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,3,withdrawn,05/27/2016,NaN,NaN,NaN,3.0,94109.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,8,complete,11/07/2016,07/18/2017,07/18/2017,2000.00,3.0,94109.0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,6,issued,11/28/2016,12/01/2017,11/20/2017,100000.00,6.0,94102.0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,8,issued,06/14/2017,07/06/2017,07/06/2017,4000.00,10.0,94107.0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,8,complete,06/30/2017,06/30/2017,06/30/2017,12000.00,5.0,94122.0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,8,issued,06/30/2017,06/30/2017,06/30/2017,0.00,10.0,94124.0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,8,issued,07/05/2017,07/05/2017,07/05/2017,1.00,5.0,94117.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,8,issued,07/06/2017,07/06/2017,07/06/2017,0.00,8.0,94117.0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,8,issued,07/06/2017,07/06/2017,07/06/2017,1.00,8.0,94114.0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,8,issued,07/07/2017,07/07/2017,07/07/2017,1.00,5.0,94102.0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,8,issued,07/10/2017,07/10/2017,07/10/2017,1.00,8.0,94114.0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,8,filed,07/25/2017,NaN,NaN,0.00,8.0,94131.0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,8,issued,07/26/2017,07/26/2017,07/26/2017,1.00,2.0,94115.0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,94108.0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,94104.0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,8.0,94114.0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,8,filed,07/28/2017,NaN,NaN,0.00,2.0,94123.0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,8,issued,07/28/2017,07/28/2017,07/28/2017,1.00,8.0,94114.0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,8,issued,07/31/2017,07/31/2017,07/31/2017,1.00,5.0,94117.0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,8,filed,08/01/2017,NaN,NaN,0.00,9.0,94110.0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,3,filed,08/01/2017,NaN,NaN,NaN,3.0,94133.0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,8,issued,08/07/2017,08/07/2017,08/07/2017,1.00,2.0,94123.0,0,0,...,1,0,0,0,0,0,0,0,0,0
24,8,issued,08/08/2017,08/08/2017,08/08/2017,64650.00,2.0,94123.0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,8,issued,08/16/2017,08/16/2017,08/16/2017,7000.00,4.0,94122.0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,8,issued,08/18/2017,08/18/2017,08/18/2017,1.00,1.0,94121.0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,5.0,94117.0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,7.0,94122.0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,8,issued,08/22/2017,08/22/2017,08/22/2017,1.00,3.0,94102.0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198856,8,filed,02/23/2018,NaN,NaN,0.00,3.0,94104.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198857,8,filed,02/23/2018,NaN,NaN,0.00,6.0,94105.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198858,8,issued,02/23/2018,02/23/2018,02/23/2018,0.00,2.0,94115.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198859,8,filed,02/23/2018,NaN,NaN,0.00,6.0,94103.0,0,1,...,0,0,0,0,0,0,0,0,0,0
198860,8,filed,02/23/2018,NaN,NaN,0.00,10.0,94107.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198861,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94108.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198862,8,filed,02/23/2018,NaN,NaN,NaN,3.0,94109.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198863,8,issued,02/23/2018,02/23/2018,02/23/2018,45000.00,5.0,94117.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198864,8,filed,02/23/2018,NaN,NaN,0.00,9.0,94110.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198865,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94118.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198866,8,filed,02/23/2018,NaN,NaN,1.00,4.0,94116.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198867,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,10.0,94107.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198868,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,9.0,94110.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198869,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94109.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198870,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,94109.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198871,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,5.0,94117.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198872,8,filed,02/23/2018,NaN,NaN,0.00,8.0,94114.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198873,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,9.0,94110.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198874,8,issued,02/23/2018,02/23/2018,02/23/2018,15000.00,8.0,94131.0,0,0,...,0,0,0,0,0,1,0,0,0,0
198875,8,filed,02/23/2018,NaN,NaN,0.00,5.0,94102.0,1,0,...,0,0,0,0,0,0,0,0,0,0
198876,8,issued,02/23/2018,02/23/2018,02/23/2018,0.00,5.0,94117.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198877,8,issued,02/23/2018,02/23/2018,02/23/2018,1000.00,11.0,94112.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198878,8,filed,02/23/2018,NaN,NaN,0.00,9.0,94110.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198879,8,issued,02/23/2018,02/23/2018,02/23/2018,18453.12,11.0,94112.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198880,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,7.0,94122.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198881,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94133.0,0,0,...,0,0,0,0,0,0,0,1,0,0
198882,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,11.0,94112.0,0,0,...,0,0,0,0,0,0,0,0,0,0
198883,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,94102.0,1,0,...,0,0,0,0,0,0,0,0,0,0
198884,8,filed,02/23/2018,NaN,NaN,1.00,6.0,94103.0,0,1,...,0,0,0,0,0,0,0,0,0,0
198885,8,filed,02/23/2018,NaN,NaN,0.00,4.0,94116.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
df8['Current Status'].unique()

array(['expired', 'issued', 'withdrawn', 'complete', 'filed', 'approved',
       'reinstated', 'cancelled', 'appeal', 'suspend', 'revoked',
       'plancheck', 'disapproved', 'incomplete'], dtype=object)

In [48]:
df8 = df8.drop(columns=['Zipcode'])

In [49]:
df8

,Permit Type,Current Status,Filed Date,Issued Date,First Construction Document Date,Revised Cost,Supervisor District,z_94102.0,z_94103.0,z_94104.0,...,z_94123.0,z_94124.0,z_94127.0,z_94129.0,z_94130.0,z_94131.0,z_94132.0,z_94133.0,z_94134.0,z_94158.0
0,4,expired,05/06/2015,11/09/2015,11/09/2015,4000.00,3.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4,issued,04/19/2016,08/03/2017,08/03/2017,500.00,3.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,withdrawn,05/27/2016,NaN,NaN,NaN,3.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,8,complete,11/07/2016,07/18/2017,07/18/2017,2000.00,3.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,6,issued,11/28/2016,12/01/2017,11/20/2017,100000.00,6.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,8,issued,06/14/2017,07/06/2017,07/06/2017,4000.00,10.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,8,complete,06/30/2017,06/30/2017,06/30/2017,12000.00,5.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,8,issued,06/30/2017,06/30/2017,06/30/2017,0.00,10.0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,8,issued,07/05/2017,07/05/2017,07/05/2017,1.00,5.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,8,issued,07/06/2017,07/06/2017,07/06/2017,0.00,8.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,8,issued,07/06/2017,07/06/2017,07/06/2017,1.00,8.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,8,issued,07/07/2017,07/07/2017,07/07/2017,1.00,5.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12,8,issued,07/10/2017,07/10/2017,07/10/2017,1.00,8.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,8,filed,07/25/2017,NaN,NaN,0.00,8.0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,8,issued,07/26/2017,07/26/2017,07/26/2017,1.00,2.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,3.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,8,issued,07/27/2017,07/27/2017,07/27/2017,1.00,8.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,8,filed,07/28/2017,NaN,NaN,0.00,2.0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,8,issued,07/28/2017,07/28/2017,07/28/2017,1.00,8.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,8,issued,07/31/2017,07/31/2017,07/31/2017,1.00,5.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,8,filed,08/01/2017,NaN,NaN,0.00,9.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,3,filed,08/01/2017,NaN,NaN,NaN,3.0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,8,issued,08/07/2017,08/07/2017,08/07/2017,1.00,2.0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24,8,issued,08/08/2017,08/08/2017,08/08/2017,64650.00,2.0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,8,issued,08/16/2017,08/16/2017,08/16/2017,7000.00,4.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,8,issued,08/18/2017,08/18/2017,08/18/2017,1.00,1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,5.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,8,issued,08/21/2017,08/21/2017,08/21/2017,1.00,7.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,8,issued,08/22/2017,08/22/2017,08/22/2017,1.00,3.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198856,8,filed,02/23/2018,NaN,NaN,0.00,3.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
198857,8,filed,02/23/2018,NaN,NaN,0.00,6.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198858,8,issued,02/23/2018,02/23/2018,02/23/2018,0.00,2.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198859,8,filed,02/23/2018,NaN,NaN,0.00,6.0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
198860,8,filed,02/23/2018,NaN,NaN,0.00,10.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198861,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198862,8,filed,02/23/2018,NaN,NaN,NaN,3.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198863,8,issued,02/23/2018,02/23/2018,02/23/2018,45000.00,5.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198864,8,filed,02/23/2018,NaN,NaN,0.00,9.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198865,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198866,8,filed,02/23/2018,NaN,NaN,1.00,4.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198867,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,10.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198868,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,9.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198869,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198870,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,2.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198871,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,5.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198872,8,filed,02/23/2018,NaN,NaN,0.00,8.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198873,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,9.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198874,8,issued,02/23/2018,02/23/2018,02/23/2018,15000.00,8.0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
198875,8,filed,02/23/2018,NaN,NaN,0.00,5.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
198876,8,issued,02/23/2018,02/23/2018,02/23/2018,0.00,5.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198877,8,issued,02/23/2018,02/23/2018,02/23/2018,1000.00,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198878,8,filed,02/23/2018,NaN,NaN,0.00,9.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198879,8,issued,02/23/2018,02/23/2018,02/23/2018,18453.12,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198880,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,7.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198881,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
198882,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198883,8,issued,02/23/2018,02/23/2018,02/23/2018,1.00,3.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
198884,8,filed,02/23/2018,NaN,NaN,1.00,6.0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
198885,8,filed,02/23/2018,NaN,NaN,0.00,4.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
df8['Permit Type'].unique()

array([4, 3, 8, 6, 7, 1, 5, 2])

In [51]:
permitTypes = pd.get_dummies( df8['Permit Type'] , prefix = 'pt' )

In [52]:
permitTypes

        pt_1  pt_2  pt_3  pt_4  pt_5  pt_6  pt_7  pt_8
0          0     0     0     1     0     0     0     0
1          0     0     0     1     0     0     0     0
2          0     0     1     0     0     0     0     0
3          0     0     0     0     0     0     0     1
4          0     0     0     0     0     1     0     0
5          0     0     0     0     0     0     0     1
6          0     0     0     0     0     0     0     1
7          0     0     0     0     0     0     0     1
8          0     0     0     0     0     0     0     1
9          0     0     0     0     0     0     0     1
10         0     0     0     0     0     0     0     1
11         0     0     0     0     0     0     0     1
12         0     0     0     0     0     0     0     1
13         0     0     0     0     0     0     0     1
14         0     0     0     0     0     0     0     1
15         0     0     0     0     0     0     0     1
16         0     0     0     0     0     0     0     1
17         0     0     0     0     0     0     0     1
18         0     0     0     0     0     0     0     1
19         0     0     0     0     0     0     0     1
20         0     0     0     0     0     0     0     1
21         0     0     0     0     0     0     0     1
22         0     0     1     0     0     0     0     0
23         0     0     0     0     0     0     0     1
24         0     0     0     0     0     0     0     1
25         0     0     0     0     0     0     0     1
26         0     0     0     0     0     0     0     1
27         0     0     0     0     0     0     0     1
28         0     0     0     0     0     0     0     1
29         0     0     0     0     0     0     0     1
...      ...   ...   ...   ...   ...   ...   ...   ...
198856     0     0     0     0     0     0     0     1
198857     0     0     0     0     0     0     0     1
198858     0     0     0     0     0     0     0     1
198859     0     0     0     0     0     0     0     1
198860     0     0     0     0     0     0     0     1
198861     0     0     0     0     0     0     0     1
198862     0     0     0     0     0     0     0     1
198863     0     0     0     0     0     0     0     1
198864     0     0     0     0     0     0     0     1
198865     0     0     0     0     0     0     0     1
198866     0     0     0     0     0     0     0     1
198867     0     0     0     0     0     0     0     1
198868     0     0     0     0     0     0     0     1
198869     0     0     0     0     0     0     0     1
198870     0     0     0     0     0     0     0     1
198871     0     0     0     0     0     0     0     1
198872     0     0     0     0     0     0     0     1
198873     0     0     0     0     0     0     0     1
198874     0     0     0     0     0     0     0     1
198875     0     0     0     0     0     0     0     1
198876     0     0     0     0     0     0     0     1
198877     0     0     0     0     0     0     0     1
198878     0     0     0     0     0     0     0     1
198879     0     0     0     0     0     0     0     1
198880     0     0     0     0     0     0     0     1
198881     0     0     0     0     0     0     0     1
198882     0     0     0     0     0     0     0     1
198883     0     0     0     0     0     0     0     1
198884     0     0     0     0     0     0     0     1
198885     0     0     0     0     0     0     0     1

[197184 rows x 8 columns]

In [53]:
sd = pd.get_dummies( df8['Supervisor District'] , prefix = 'sd' )

In [54]:
sd

,sd_1.0,sd_2.0,sd_3.0,sd_4.0,sd_5.0,sd_6.0,sd_7.0,sd_8.0,sd_9.0,sd_10.0,sd_11.0
0,0,0,1,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,1,0
6,0,0,0,0,1,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,1,0
8,0,0,0,0,1,0,0,0,0,0,0
9,0,0,0,0,0,0,0,1,0,0,0
10,0,0,0,0,0,0,0,1,0,0,0
11,0,0,0,0,1,0,0,0,0,0,0
12,0,0,0,0,0,0,0,1,0,0,0
13,0,0,0,0,0,0,0,1,0,0,0
14,0,1,0,0,0,0,0,0,0,0,0
15,0,0,1,0,0,0,0,0,0,0,0
16,0,0,1,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,1,0,0,0
18,0,1,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,1,0,0,0
20,0,0,0,0,1,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,1,0,0
22,0,0,1,0,0,0,0,0,0,0,0
23,0,1,0,0,0,0,0,0,0,0,0
24,0,1,0,0,0,0,0,0,0,0,0
25,0,0,0,1,0,0,0,0,0,0,0
26,1,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,1,0,0,0,0,0,0
28,0,0,0,0,0,0,1,0,0,0,0
29,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
198856,0,0,1,0,0,0,0,0,0,0,0
198857,0,0,0,0,0,1,0,0,0,0,0
198858,0,1,0,0,0,0,0,0,0,0,0
198859,0,0,0,0,0,1,0,0,0,0,0
198860,0,0,0,0,0,0,0,0,0,1,0
198861,0,0,1,0,0,0,0,0,0,0,0
198862,0,0,1,0,0,0,0,0,0,0,0
198863,0,0,0,0,1,0,0,0,0,0,0
198864,0,0,0,0,0,0,0,0,1,0,0
198865,0,1,0,0,0,0,0,0,0,0,0
198866,0,0,0,1,0,0,0,0,0,0,0
198867,0,0,0,0,0,0,0,0,0,1,0
198868,0,0,0,0,0,0,0,0,1,0,0
198869,0,1,0,0,0,0,0,0,0,0,0
198870,0,1,0,0,0,0,0,0,0,0,0
198871,0,0,0,0,1,0,0,0,0,0,0
198872,0,0,0,0,0,0,0,1,0,0,0
198873,0,0,0,0,0,0,0,0,1,0,0
198874,0,0,0,0,0,0,0,1,0,0,0
198875,0,0,0,0,1,0,0,0,0,0,0
198876,0,0,0,0,1,0,0,0,0,0,0
198877,0,0,0,0,0,0,0,0,0,0,1
198878,0,0,0,0,0,0,0,0,1,0,0
198879,0,0,0,0,0,0,0,0,0,0,1
198880,0,0,0,0,0,0,1,0,0,0,0
198881,0,0,1,0,0,0,0,0,0,0,0
198882,0,0,0,0,0,0,0,0,0,0,1
198883,0,0,1,0,0,0,0,0,0,0,0
198884,0,0,0,0,0,1,0,0,0,0,0
198885,0,0,0,1,0,0,0,0,0,0,0

In [55]:
df8 = df8.drop(columns=['Permit Type','Supervisor District'])

In [56]:
df8=pd.concat([df8, permitTypes], axis=1)

In [57]:
df8=pd.concat([df8, sd], axis=1)

In [58]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 197184 entries, 0 to 198885
Data columns (total 51 columns):
Current Status                      197184 non-null object
Filed Date                          197184 non-null object
Issued Date                         182304 non-null object
First Construction Document Date    182298 non-null object
Revised Cost                        191132 non-null float64
z_94102.0                           197184 non-null uint8
z_94103.0                           197184 non-null uint8
z_94104.0                           197184 non-null uint8
z_94105.0                           197184 non-null uint8
z_94107.0                           197184 non-null uint8
z_94108.0                           197184 non-null uint8
z_94109.0                           197184 non-null uint8
z_94110.0                           197184 non-null uint8
z_94111.0                           197184 non-null uint8
z_94112.0                           197184 non-null uint8
z_94114.0                           197184 non-null uint8
z_94115.0                           197184 non-null uint8
z_94116.0                           197184 non-null uint8
z_94117.0                           197184 non-null uint8
z_94118.0                           197184 non-null uint8
z_94121.0                           197184 non-null uint8
z_94122.0                           197184 non-null uint8
z_94123.0                           197184 non-null uint8
z_94124.0                           197184 non-null uint8
z_94127.0                           197184 non-null uint8
z_94129.0                           197184 non-null uint8
z_94130.0                           197184 non-null uint8
z_94131.0                           197184 non-null uint8
z_94132.0                           197184 non-null uint8
z_94133.0                           197184 non-null uint8
z_94134.0                           197184 non-null uint8
z_94158.0                           197184 non-null uint8
pt_1                                197184 non-null uint8
pt_2                                197184 non-null uint8
pt_3                                197184 non-null uint8
pt_4                                197184 non-null uint8
pt_5                                197184 non-null uint8
pt_6                                197184 non-null uint8
pt_7                                197184 non-null uint8
pt_8                                197184 non-null uint8
sd_1.0                              197184 non-null uint8
sd_2.0                              197184 non-null uint8
sd_3.0                              197184 non-null uint8
sd_4.0                              197184 non-null uint8
sd_5.0                              197184 non-null uint8
sd_6.0                              197184 non-null uint8
sd_7.0                              197184 non-null uint8
sd_8.0                              197184 non-null uint8
sd_9.0                              197184 non-null uint8
sd_10.0                             197184 non-null uint8
sd_11.0                             197184 non-null uint8
dtypes: float64(1), object(4), uint8(46)
memory usage: 17.7+ MB

In [59]:
#df8 = df8.drop(columns=['Current Status'])

In [60]:
#df8=pd.concat([df8, status], axis=1)

In [61]:
df8 = df8.drop(columns=['First Construction Document Date'])
#df8 = df8.drop(columns=['First Construction Document Date','Permit Creation Date','Current Status Date'])

In [62]:
df8

,Current Status,Filed Date,Issued Date,Revised Cost,z_94102.0,z_94103.0,z_94104.0,z_94105.0,z_94107.0,z_94108.0,...,sd_2.0,sd_3.0,sd_4.0,sd_5.0,sd_6.0,sd_7.0,sd_8.0,sd_9.0,sd_10.0,sd_11.0
0,expired,05/06/2015,11/09/2015,4000.00,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,issued,04/19/2016,08/03/2017,500.00,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,withdrawn,05/27/2016,NaN,NaN,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,complete,11/07/2016,07/18/2017,2000.00,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,issued,11/28/2016,12/01/2017,100000.00,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,issued,06/14/2017,07/06/2017,4000.00,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
6,complete,06/30/2017,06/30/2017,12000.00,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
7,issued,06/30/2017,06/30/2017,0.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8,issued,07/05/2017,07/05/2017,1.00,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,issued,07/06/2017,07/06/2017,0.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
10,issued,07/06/2017,07/06/2017,1.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
11,issued,07/07/2017,07/07/2017,1.00,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
12,issued,07/10/2017,07/10/2017,1.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13,filed,07/25/2017,NaN,0.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,issued,07/26/2017,07/26/2017,1.00,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
15,issued,07/27/2017,07/27/2017,1.00,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
16,issued,07/27/2017,07/27/2017,1.00,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,issued,07/27/2017,07/27/2017,1.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
18,filed,07/28/2017,NaN,0.00,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,issued,07/28/2017,07/28/2017,1.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,issued,07/31/2017,07/31/2017,1.00,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
21,filed,08/01/2017,NaN,0.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
22,filed,08/01/2017,NaN,NaN,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
23,issued,08/07/2017,08/07/2017,1.00,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24,issued,08/08/2017,08/08/2017,64650.00,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,issued,08/16/2017,08/16/2017,7000.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
26,issued,08/18/2017,08/18/2017,1.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,issued,08/21/2017,08/21/2017,1.00,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
28,issued,08/21/2017,08/21/2017,1.00,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
29,issued,08/22/2017,08/22/2017,1.00,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198856,filed,02/23/2018,NaN,0.00,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
198857,filed,02/23/2018,NaN,0.00,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
198858,issued,02/23/2018,02/23/2018,0.00,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
198859,filed,02/23/2018,NaN,0.00,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
198860,filed,02/23/2018,NaN,0.00,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
198861,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
198862,filed,02/23/2018,NaN,NaN,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
198863,issued,02/23/2018,02/23/2018,45000.00,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198864,filed,02/23/2018,NaN,0.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
198865,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
198866,filed,02/23/2018,NaN,1.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
198867,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
198868,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
198869,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
198870,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
198871,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198872,filed,02/23/2018,NaN,0.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
198873,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
198874,issued,02/23/2018,02/23/2018,15000.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
198875,filed,02/23/2018,NaN,0.00,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198876,issued,02/23/2018,02/23/2018,0.00,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198877,issued,02/23/2018,02/23/2018,1000.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198878,filed,02/23/2018,NaN,0.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
198879,issued,02/23/2018,02/23/2018,18453.12,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198880,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
198881,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
198882,issued,02/23/2018,02/23/2018,1.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198883,issued,02/23/2018,02/23/2018,1.00,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
198884,filed,02/23/2018,NaN,1.00,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
198885,filed,02/23/2018,NaN,0.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [63]:
#df8 = df8.dropna()

In [64]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 197184 entries, 0 to 198885
Data columns (total 50 columns):
Current Status    197184 non-null object
Filed Date        197184 non-null object
Issued Date       182304 non-null object
Revised Cost      191132 non-null float64
z_94102.0         197184 non-null uint8
z_94103.0         197184 non-null uint8
z_94104.0         197184 non-null uint8
z_94105.0         197184 non-null uint8
z_94107.0         197184 non-null uint8
z_94108.0         197184 non-null uint8
z_94109.0         197184 non-null uint8
z_94110.0         197184 non-null uint8
z_94111.0         197184 non-null uint8
z_94112.0         197184 non-null uint8
z_94114.0         197184 non-null uint8
z_94115.0         197184 non-null uint8
z_94116.0         197184 non-null uint8
z_94117.0         197184 non-null uint8
z_94118.0         197184 non-null uint8
z_94121.0         197184 non-null uint8
z_94122.0         197184 non-null uint8
z_94123.0         197184 non-null uint8
z_94124.0         197184 non-null uint8
z_94127.0         197184 non-null uint8
z_94129.0         197184 non-null uint8
z_94130.0         197184 non-null uint8
z_94131.0         197184 non-null uint8
z_94132.0         197184 non-null uint8
z_94133.0         197184 non-null uint8
z_94134.0         197184 non-null uint8
z_94158.0         197184 non-null uint8
pt_1              197184 non-null uint8
pt_2              197184 non-null uint8
pt_3              197184 non-null uint8
pt_4              197184 non-null uint8
pt_5              197184 non-null uint8
pt_6              197184 non-null uint8
pt_7              197184 non-null uint8
pt_8              197184 non-null uint8
sd_1.0            197184 non-null uint8
sd_2.0            197184 non-null uint8
sd_3.0            197184 non-null uint8
sd_4.0            197184 non-null uint8
sd_5.0            197184 non-null uint8
sd_6.0            197184 non-null uint8
sd_7.0            197184 non-null uint8
sd_8.0            197184 non-null uint8
sd_9.0            197184 non-null uint8
sd_10.0           197184 non-null uint8
sd_11.0           197184 non-null uint8
dtypes: float64(1), object(3), uint8(46)
memory usage: 16.2+ MB

In [65]:
df8['Current Status'].unique()

array(['expired', 'issued', 'withdrawn', 'complete', 'filed', 'approved',
       'reinstated', 'cancelled', 'appeal', 'suspend', 'revoked',
       'plancheck', 'disapproved', 'incomplete'], dtype=object)

In [66]:
#sf_pemits2['Current Status'].unique()

In [67]:
df_filed = df8.loc[df8['Current Status'].isin(['filed'])]

In [68]:
df_filed['Current Status'].unique()

array(['filed'], dtype=object)

In [70]:
df8['Current Status'].unique()
df_completed = df8.loc[df8['Current Status'].isin(['complete','issued'])]

In [71]:
df_completed['Current Status'].unique()

array(['issued', 'complete'], dtype=object)

In [72]:
df99 = df_completed

In [73]:
df99['from_date']=pd.to_datetime(df99['Filed Date'])

/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [75]:
df99['to_date']=pd.to_datetime(df99['Issued Date'])

/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [76]:
df99['process_time']=df99['to_date']-df99['from_date']

/home/neil/.local/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [77]:
df99.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 179000 entries, 1 to 198883
Data columns (total 53 columns):
Current Status    179000 non-null object
Filed Date        179000 non-null object
Issued Date       178982 non-null object
Revised Cost      178989 non-null float64
z_94102.0         179000 non-null uint8
z_94103.0         179000 non-null uint8
z_94104.0         179000 non-null uint8
z_94105.0         179000 non-null uint8
z_94107.0         179000 non-null uint8
z_94108.0         179000 non-null uint8
z_94109.0         179000 non-null uint8
z_94110.0         179000 non-null uint8
z_94111.0         179000 non-null uint8
z_94112.0         179000 non-null uint8
z_94114.0         179000 non-null uint8
z_94115.0         179000 non-null uint8
z_94116.0         179000 non-null uint8
z_94117.0         179000 non-null uint8
z_94118.0         179000 non-null uint8
z_94121.0         179000 non-null uint8
z_94122.0         179000 non-null uint8
z_94123.0         179000 non-null uint8
z_94124.0         179000 non-null uint8
z_94127.0         179000 non-null uint8
z_94129.0         179000 non-null uint8
z_94130.0         179000 non-null uint8
z_94131.0         179000 non-null uint8
z_94132.0         179000 non-null uint8
z_94133.0         179000 non-null uint8
z_94134.0         179000 non-null uint8
z_94158.0         179000 non-null uint8
pt_1              179000 non-null uint8
pt_2              179000 non-null uint8
pt_3              179000 non-null uint8
pt_4              179000 non-null uint8
pt_5              179000 non-null uint8
pt_6              179000 non-null uint8
pt_7              179000 non-null uint8
pt_8              179000 non-null uint8
sd_1.0            179000 non-null uint8
sd_2.0            179000 non-null uint8
sd_3.0            179000 non-null uint8
sd_4.0            179000 non-null uint8
sd_5.0            179000 non-null uint8
sd_6.0            179000 non-null uint8
sd_7.0            179000 non-null uint8
sd_8.0            179000 non-null uint8
sd_9.0            179000 non-null uint8
sd_10.0           179000 non-null uint8
sd_11.0           179000 non-null uint8
from_date         179000 non-null datetime64[ns]
to_date           178982 non-null datetime64[ns]
process_time      178982 non-null timedelta64[ns]
dtypes: datetime64[ns](2), float64(1), object(3), timedelta64[ns](1), uint8(46)
memory usage: 23.8+ MB

In [78]:
df99=df99.drop(columns=['Filed Date','Issued Date','from_date','to_date'])

In [79]:
df99['process_time']

1         471 days
3         253 days
4         368 days
5          22 days
6           0 days
7           0 days
8           0 days
9           0 days
10          0 days
11          0 days
12          0 days
14          0 days
15          0 days
16          0 days
17          0 days
19          0 days
20          0 days
23          0 days
24          0 days
25          0 days
26          0 days
27          0 days
28          0 days
29          0 days
30          0 days
31          0 days
32          0 days
34          0 days
35          0 days
36          0 days
            ...
198835      0 days
198837      0 days
198840      0 days
198841      0 days
198842      0 days
198843      0 days
198844      0 days
198845      0 days
198846      0 days
198847      0 days
198850      0 days
198851   1045 days
198858      0 days
198861      0 days
198863      0 days
198865      0 days
198867      0 days
198868      0 days
198869      0 days
198870      0 days
198871      0 days
198873      0 days
198874      0 days
198876      0 days
198877      0 days
198879      0 days
198880      0 days
198881      0 days
198882      0 days
198883      0 days
Name: process_time, Length: 179000, dtype: timedelta64[ns]

In [80]:
df99['total_time']=df99['process_time'].astype('timedelta64[D]')

In [81]:
df99=df99.drop(columns=['process_time'])

In [82]:
df99.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 179000 entries, 1 to 198883
Data columns (total 49 columns):
Current Status    179000 non-null object
Revised Cost      178989 non-null float64
z_94102.0         179000 non-null uint8
z_94103.0         179000 non-null uint8
z_94104.0         179000 non-null uint8
z_94105.0         179000 non-null uint8
z_94107.0         179000 non-null uint8
z_94108.0         179000 non-null uint8
z_94109.0         179000 non-null uint8
z_94110.0         179000 non-null uint8
z_94111.0         179000 non-null uint8
z_94112.0         179000 non-null uint8
z_94114.0         179000 non-null uint8
z_94115.0         179000 non-null uint8
z_94116.0         179000 non-null uint8
z_94117.0         179000 non-null uint8
z_94118.0         179000 non-null uint8
z_94121.0         179000 non-null uint8
z_94122.0         179000 non-null uint8
z_94123.0         179000 non-null uint8
z_94124.0         179000 non-null uint8
z_94127.0         179000 non-null uint8
z_94129.0         179000 non-null uint8
z_94130.0         179000 non-null uint8
z_94131.0         179000 non-null uint8
z_94132.0         179000 non-null uint8
z_94133.0         179000 non-null uint8
z_94134.0         179000 non-null uint8
z_94158.0         179000 non-null uint8
pt_1              179000 non-null uint8
pt_2              179000 non-null uint8
pt_3              179000 non-null uint8
pt_4              179000 non-null uint8
pt_5              179000 non-null uint8
pt_6              179000 non-null uint8
pt_7              179000 non-null uint8
pt_8              179000 non-null uint8
sd_1.0            179000 non-null uint8
sd_2.0            179000 non-null uint8
sd_3.0            179000 non-null uint8
sd_4.0            179000 non-null uint8
sd_5.0            179000 non-null uint8
sd_6.0            179000 non-null uint8
sd_7.0            179000 non-null uint8
sd_8.0            179000 non-null uint8
sd_9.0            179000 non-null uint8
sd_10.0           179000 non-null uint8
sd_11.0           179000 non-null uint8
total_time        178982 non-null float64
dtypes: float64(2), object(1), uint8(46)
memory usage: 18.3+ MB

In [84]:
df99=df99.drop(columns=['Current Status'])

In [96]:
df99.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 179000 entries, 1 to 198883
Data columns (total 48 columns):
Revised Cost    178989 non-null float64
z_94102.0       179000 non-null uint8
z_94103.0       179000 non-null uint8
z_94104.0       179000 non-null uint8
z_94105.0       179000 non-null uint8
z_94107.0       179000 non-null uint8
z_94108.0       179000 non-null uint8
z_94109.0       179000 non-null uint8
z_94110.0       179000 non-null uint8
z_94111.0       179000 non-null uint8
z_94112.0       179000 non-null uint8
z_94114.0       179000 non-null uint8
z_94115.0       179000 non-null uint8
z_94116.0       179000 non-null uint8
z_94117.0       179000 non-null uint8
z_94118.0       179000 non-null uint8
z_94121.0       179000 non-null uint8
z_94122.0       179000 non-null uint8
z_94123.0       179000 non-null uint8
z_94124.0       179000 non-null uint8
z_94127.0       179000 non-null uint8
z_94129.0       179000 non-null uint8
z_94130.0       179000 non-null uint8
z_94131.0       179000 non-null uint8
z_94132.0       179000 non-null uint8
z_94133.0       179000 non-null uint8
z_94134.0       179000 non-null uint8
z_94158.0       179000 non-null uint8
pt_1            179000 non-null uint8
pt_2            179000 non-null uint8
pt_3            179000 non-null uint8
pt_4            179000 non-null uint8
pt_5            179000 non-null uint8
pt_6            179000 non-null uint8
pt_7            179000 non-null uint8
pt_8            179000 non-null uint8
sd_1.0          179000 non-null uint8
sd_2.0          179000 non-null uint8
sd_3.0          179000 non-null uint8
sd_4.0          179000 non-null uint8
sd_5.0          179000 non-null uint8
sd_6.0          179000 non-null uint8
sd_7.0          179000 non-null uint8
sd_8.0          179000 non-null uint8
sd_9.0          179000 non-null uint8
sd_10.0         179000 non-null uint8
sd_11.0         179000 non-null uint8
total_time      178982 non-null float64
dtypes: float64(2), uint8(46)
memory usage: 16.9 MB

In [97]:
df999=df99.dropna()

In [121]:
df999

,Revised Cost,z_94102.0,z_94103.0,z_94104.0,z_94105.0,z_94107.0,z_94108.0,z_94109.0,z_94110.0,z_94111.0,...,sd_3.0,sd_4.0,sd_5.0,sd_6.0,sd_7.0,sd_8.0,sd_9.0,sd_10.0,sd_11.0,total_time
1,500.00,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,471.0
3,2000.00,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,253.0
4,100000.00,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,368.0
5,4000.00,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,22.0
6,12000.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
7,0.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0.0
8,1.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
9,0.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
10,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
11,1.00,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
12,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
14,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
15,1.00,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0.0
16,1.00,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0.0
17,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
19,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
20,1.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
23,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
24,64650.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
25,7000.00,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0.0
26,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
27,1.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
28,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0.0
29,1.00,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0.0
30,1.00,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0.0
31,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
32,0.00,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0.0
34,1.00,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
35,1.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
36,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198835,22000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0.0
198837,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
198840,1.00,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0.0
198841,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
198842,1.00,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0.0
198843,1.00,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
198844,8000.00,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0.0
198845,13000.00,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0.0
198846,5000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
198847,1.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
198850,1.00,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0.0
198851,500000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1045.0
198858,0.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
198861,1.00,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0.0
198863,45000.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
198865,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
198867,1.00,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0.0
198868,1.00,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0.0
198869,1.00,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0.0
198870,1.00,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0.0
198871,1.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
198873,1.00,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0.0
198874,15000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0.0
198876,0.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0.0
198877,1000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0.0
198879,18453.12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0.0
198880,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0.0
198881,1.00,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0.0
198882,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0.0
198883,1.00,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0.0

In [100]:
# ML Algorithm

In [101]:
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [102]:
reg=linear_model.LinearRegression()

In [103]:
#df_x=df7[['Permit Type','Permit Creation Date66','Current Status','Current Status Date66','Filed Date66','Zipcode','Revised Cost','Supervisor District']].copy()
#df_y=df7['Issued Date66']
df_x=df999.drop(columns=['total_time'])
df_y=df999['total_time']

In [120]:
df_x.columns

Index(['Revised Cost', 'z_94102.0', 'z_94103.0', 'z_94104.0', 'z_94105.0',
       'z_94107.0', 'z_94108.0', 'z_94109.0', 'z_94110.0', 'z_94111.0',
       'z_94112.0', 'z_94114.0', 'z_94115.0', 'z_94116.0', 'z_94117.0',
       'z_94118.0', 'z_94121.0', 'z_94122.0', 'z_94123.0', 'z_94124.0',
       'z_94127.0', 'z_94129.0', 'z_94130.0', 'z_94131.0', 'z_94132.0',
       'z_94133.0', 'z_94134.0', 'z_94158.0', 'pt_1', 'pt_2', 'pt_3', 'pt_4',
       'pt_5', 'pt_6', 'pt_7', 'pt_8', 'sd_1.0', 'sd_2.0', 'sd_3.0', 'sd_4.0',
       'sd_5.0', 'sd_6.0', 'sd_7.0', 'sd_8.0', 'sd_9.0', 'sd_10.0', 'sd_11.0'],
      dtype='object')

In [104]:
df_x

,Revised Cost,z_94102.0,z_94103.0,z_94104.0,z_94105.0,z_94107.0,z_94108.0,z_94109.0,z_94110.0,z_94111.0,...,sd_2.0,sd_3.0,sd_4.0,sd_5.0,sd_6.0,sd_7.0,sd_8.0,sd_9.0,sd_10.0,sd_11.0
1,500.00,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,2000.00,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
4,100000.00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,4000.00,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,12000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
7,0.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,0.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
10,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
11,1.00,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
12,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,1.00,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
15,1.00,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
16,1.00,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
19,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23,1.00,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24,64650.00,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,7000.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
26,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
28,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
29,1.00,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
30,1.00,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
31,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32,0.00,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
34,1.00,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
35,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
36,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198835,22000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198837,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198840,1.00,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
198841,1.00,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
198842,1.00,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
198843,1.00,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198844,8000.00,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
198845,13000.00,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
198846,5000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
198847,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198850,1.00,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
198851,500000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
198858,0.00,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
198861,1.00,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
198863,45000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198865,1.00,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
198867,1.00,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
198868,1.00,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
198869,1.00,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
198870,1.00,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
198871,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198873,1.00,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
198874,15000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
198876,0.00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
198877,1000.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198879,18453.12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198880,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
198881,1.00,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
198882,1.00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
198883,1.00,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [105]:
x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size=0.2,random_state=4)

In [106]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 143178 entries, 102638 to 124952
Data columns (total 47 columns):
Revised Cost    143178 non-null float64
z_94102.0       143178 non-null uint8
z_94103.0       143178 non-null uint8
z_94104.0       143178 non-null uint8
z_94105.0       143178 non-null uint8
z_94107.0       143178 non-null uint8
z_94108.0       143178 non-null uint8
z_94109.0       143178 non-null uint8
z_94110.0       143178 non-null uint8
z_94111.0       143178 non-null uint8
z_94112.0       143178 non-null uint8
z_94114.0       143178 non-null uint8
z_94115.0       143178 non-null uint8
z_94116.0       143178 non-null uint8
z_94117.0       143178 non-null uint8
z_94118.0       143178 non-null uint8
z_94121.0       143178 non-null uint8
z_94122.0       143178 non-null uint8
z_94123.0       143178 non-null uint8
z_94124.0       143178 non-null uint8
z_94127.0       143178 non-null uint8
z_94129.0       143178 non-null uint8
z_94130.0       143178 non-null uint8
z_94131.0       143178 non-null uint8
z_94132.0       143178 non-null uint8
z_94133.0       143178 non-null uint8
z_94134.0       143178 non-null uint8
z_94158.0       143178 non-null uint8
pt_1            143178 non-null uint8
pt_2            143178 non-null uint8
pt_3            143178 non-null uint8
pt_4            143178 non-null uint8
pt_5            143178 non-null uint8
pt_6            143178 non-null uint8
pt_7            143178 non-null uint8
pt_8            143178 non-null uint8
sd_1.0          143178 non-null uint8
sd_2.0          143178 non-null uint8
sd_3.0          143178 non-null uint8
sd_4.0          143178 non-null uint8
sd_5.0          143178 non-null uint8
sd_6.0          143178 non-null uint8
sd_7.0          143178 non-null uint8
sd_8.0          143178 non-null uint8
sd_9.0          143178 non-null uint8
sd_10.0         143178 non-null uint8
sd_11.0         143178 non-null uint8
dtypes: float64(1), uint8(46)
memory usage: 8.5 MB

In [107]:
#x_train['Neighborhoods - Analysis Boundaries'] = x_train['Neighborhoods - Analysis Boundaries'].astype('String')

In [108]:
model = reg.fit(x_train,y_train)

In [109]:
reg.coef_

array([  4.38566260e-08,   6.01577041e+00,   1.70274695e+00,
        -3.44684605e+00,   3.10034050e+00,   3.85115231e+00,
         8.97668232e-01,   3.19842800e+00,   7.50249858e-01,
        -4.22559190e+00,  -3.60165511e+00,   7.17805440e-01,
         2.23300047e+00,   3.25897102e+00,   4.05269827e+00,
         4.84928572e+00,   7.95364787e+00,   3.62608964e+00,
         5.37471078e+00,  -1.25630937e+01,   2.76182379e+00,
        -8.45194023e-01,  -3.62063786e+00,   2.64975230e+00,
        -1.52313351e+01,  -6.63801382e-01,  -2.82314537e+00,
        -9.97284108e+00,   2.49024092e+02,   1.77084149e+02,
         4.02810585e+01,  -1.52978861e+02,  -9.94722554e+01,
         1.40220996e+02,  -1.59145183e+02,  -1.95013995e+02,
        -2.25235908e+00,  -1.61438649e+00,   4.28551410e+00,
         9.39820556e-01,  -7.67838237e-01,  -2.84027612e+00,
        -7.62439182e-01,   2.80379187e+00,   5.50453218e+00,
         3.58132817e+00,   9.79823485e+00])

In [123]:
sf_pemits2

,Permit Type,Permit Creation Date,Current Status,Current Status Date,Filed Date,Issued Date,Completed Date,First Construction Document Date,Permit Expiration Date,Estimated Cost,Revised Cost,Supervisor District,Zipcode
0,4,05/06/2015,expired,12/21/2017,05/06/2015,11/09/2015,NaN,11/09/2015,11/03/2016,4000.00,4000.00,3.0,94102.0
1,4,04/19/2016,issued,08/03/2017,04/19/2016,08/03/2017,NaN,08/03/2017,12/03/2017,1.00,500.00,3.0,94102.0
2,3,05/27/2016,withdrawn,09/26/2017,05/27/2016,NaN,NaN,NaN,NaN,20000.00,NaN,3.0,94109.0
3,8,11/07/2016,complete,07/24/2017,11/07/2016,07/18/2017,07/24/2017,07/18/2017,07/13/2018,2000.00,2000.00,3.0,94109.0
4,6,11/28/2016,issued,12/01/2017,11/28/2016,12/01/2017,NaN,11/20/2017,12/01/2018,100000.00,100000.00,6.0,94102.0
5,8,06/14/2017,issued,07/06/2017,06/14/2017,07/06/2017,NaN,07/06/2017,07/01/2018,4000.00,4000.00,10.0,94107.0
6,8,06/30/2017,complete,07/12/2017,06/30/2017,06/30/2017,07/12/2017,06/30/2017,06/25/2018,12000.00,12000.00,5.0,94122.0
7,8,06/30/2017,issued,06/30/2017,06/30/2017,06/30/2017,NaN,06/30/2017,NaN,NaN,0.00,10.0,94124.0
8,8,07/05/2017,issued,07/05/2017,07/05/2017,07/05/2017,NaN,07/05/2017,NaN,NaN,1.00,5.0,94117.0
9,8,07/06/2017,issued,07/06/2017,07/06/2017,07/06/2017,NaN,07/06/2017,NaN,NaN,0.00,8.0,94117.0
10,8,07/06/2017,issued,07/06/2017,07/06/2017,07/06/2017,NaN,07/06/2017,NaN,NaN,1.00,8.0,94114.0
11,8,07/07/2017,issued,07/07/2017,07/07/2017,07/07/2017,NaN,07/07/2017,NaN,NaN,1.00,5.0,94102.0
12,8,07/10/2017,issued,07/10/2017,07/10/2017,07/10/2017,NaN,07/10/2017,NaN,NaN,1.00,8.0,94114.0
13,8,07/25/2017,filed,07/25/2017,07/25/2017,NaN,NaN,NaN,NaN,30000.00,0.00,8.0,94131.0
14,8,07/26/2017,issued,07/26/2017,07/26/2017,07/26/2017,NaN,07/26/2017,NaN,NaN,1.00,2.0,94115.0
15,8,07/27/2017,issued,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN,NaN,1.00,3.0,94108.0
16,8,07/27/2017,issued,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN,NaN,1.00,3.0,94104.0
17,8,07/27/2017,issued,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN,NaN,1.00,8.0,94114.0
18,8,07/28/2017,filed,07/28/2017,07/28/2017,NaN,NaN,NaN,NaN,75000.00,0.00,2.0,94123.0
19,8,07/28/2017,issued,07/28/2017,07/28/2017,07/28/2017,NaN,07/28/2017,NaN,NaN,1.00,8.0,94114.0
20,8,07/31/2017,issued,07/31/2017,07/31/2017,07/31/2017,NaN,07/31/2017,NaN,NaN,1.00,5.0,94117.0
21,8,08/01/2017,filed,08/01/2017,08/01/2017,NaN,NaN,NaN,NaN,100000.00,0.00,9.0,94110.0
22,3,08/01/2017,filed,08/01/2017,08/01/2017,NaN,NaN,NaN,NaN,100000.00,NaN,3.0,94133.0
23,8,08/07/2017,issued,08/07/2017,08/07/2017,08/07/2017,NaN,08/07/2017,NaN,NaN,1.00,2.0,94123.0
24,8,08/08/2017,issued,08/08/2017,08/08/2017,08/08/2017,NaN,08/08/2017,08/08/2018,64650.00,64650.00,2.0,94123.0
25,8,08/16/2017,issued,08/16/2017,08/16/2017,08/16/2017,NaN,08/16/2017,02/16/2018,7000.00,7000.00,4.0,94122.0
26,8,08/18/2017,issued,08/18/2017,08/18/2017,08/18/2017,NaN,08/18/2017,NaN,NaN,1.00,1.0,94121.0
27,8,08/21/2017,issued,08/21/2017,08/21/2017,08/21/2017,NaN,08/21/2017,NaN,NaN,1.00,5.0,94117.0
28,8,08/21/2017,issued,08/21/2017,08/21/2017,08/21/2017,NaN,08/21/2017,NaN,NaN,1.00,7.0,94122.0
29,8,08/22/2017,issued,08/22/2017,08/22/2017,08/22/2017,NaN,08/22/2017,NaN,NaN,1.00,3.0,94102.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,2.0,94109.0
198871,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,5.0,94117.0
198872,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,10000.00,0.00,8.0,94114.0
198873,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,06/23/2018,1.00,1.00,9.0,94110.0
198874,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,08/23/2018,10000.00,15000.00,8.0,94131.0
198875,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,1.00,0.00,5.0,94102.0
198876,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,0.00,5.0,94117.0
198877,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,06/23/2018,1000.00,1000.00,11.0,94112.0
198878,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,20000.00,0.00,9.0,94110.0
198879,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,08/23/2018,18453.12,18453.12,11.0,94112.0
198880,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,7.0,94122.0
198881,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,3.0,94133.0
198882,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,06/23/2018,1.00,1.00,11.0,94112.0
198883,8,02/23/2018,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,1.00,3.0,94102.0
198884,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,NaN,1.00,6.0,94103.0
198885,8,02/23/2018,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,5000.00,0.00,4.0,94116.0
198886,3,09/06/2017,approved,01/11/2018,09/06/2017,NaN,NaN,NaN,NaN,65000.00,65000.00,NaN,NaN
198887,8,10/04/2017,complete,12/06/2017,10/04/2017,11/03/2017,12/06/2017,11/03/2017,11/03/2018,30000.00,30000.00,NaN,NaN
198888,8,10/11/2017,complete,12/07/2017,10/11/2017,10/12/2017,12/07/2017,10/12/2017,10/12/2018,18000.00,30000.00,NaN,NaN
198889,8,10/24/2017,complete,12/05/2017,10/24/2017,10/24/2017,12/05/2017,10/24/2017,04/24/2018,20000.00,20000.00,NaN,NaN
198890,3,11/27/2017,filed,11/27/2017,11/27/2017,NaN,NaN,NaN,NaN,750000.00,750000.00,NaN,NaN
198891,8,11/27/2017,issued,12/08/2017,11/27/2017,12/08/2017,NaN,12/08/2017,04/08/2018,1.00,1.00,NaN,NaN
198892,8,12/04/2017,issued,01/16/2018,12/04/2017,01/16/2018,NaN,01/16/2018,01/16/2019,55000.00,38000.00,NaN,NaN
198893,8,12/05/2017,complete,01/22/2018,12/05/2017,12/05/2017,01/22/2018,12/05/2017,04/05/2018,2800.00,2800.00,NaN,NaN
198894,8,12/05/2017,issued,12/05/2017,12/05/2017,12/05/2017,NaN,12/05/2017,06/05/2018,7400.00,7400.00,NaN,NaN
198895,8,12/05/2017,issued,12/05/2017,12/05/2017,12/05/2017,NaN,12/05/2017,NaN,NaN,1.00,NaN,NaN
198896,8,12/05/2017,issued,12/06/2017,12/05/2017,12/06/2017,NaN,12/06/2017,04/06/2018,5000.00,5000.00,NaN,NaN
198897,8,12/06/2017,issued,12/06/2017,12/06/2017,12/06/2017,NaN,12/06/2017,NaN,NaN,1.00,NaN,NaN
198898,8,12/06/2017,issued,12/06/2017,12/06/2017,12/06/2017,NaN,12/06/2017,NaN,NaN,1.00,NaN,NaN
198899,8,12/07/2017,issued,12/07/2017,12/07/2017,12/07/2017,NaN,12/07/2017,NaN,NaN,1.00,NaN,NaN

In [ ]:
df_s = sf_pemits2[[]]

In [110]:
a=reg.predict(x_test)

In [111]:
a

array([  11.6264429 ,   34.14187635,   13.80174876, ...,   11.38532   ,
        247.60088368,   11.33695887])

In [112]:
y_test # here first column is index, row number

132477     71.0
29586      33.0
146230      0.0
148025      1.0
74849       0.0
189827     17.0
80761       0.0
66022     144.0
109741      0.0
169498      0.0
59788       0.0
63300       1.0
115752      0.0
198230      0.0
64390       0.0
39348      55.0
136717      5.0
158651      0.0
87860       0.0
15921       0.0
44384       0.0
153706      0.0
104334      7.0
77188      49.0
39426       0.0
97035     517.0
157733      0.0
114352      1.0
17219       0.0
167397     58.0
          ...
189285      1.0
81291     700.0
30397       0.0
42165       0.0
153612      0.0
63927       0.0
169818    181.0
113879     29.0
22941       0.0
173422      0.0
53496       0.0
133532      0.0
127161    126.0
166225     15.0
49851      23.0
9210      111.0
44186       0.0
164154      0.0
189181      6.0
140931      0.0
171134    785.0
89947       0.0
192174      3.0
188349      0.0
169286      0.0
154357      0.0
134411     29.0
140810      0.0
875       442.0
62559       0.0
Name: total_time, Length: 35795, dtype: float64

In [113]:
model.score(x_test,y_test)

0.42615959537773318

In [114]:
#a.shape

In [115]:
#c, r = a.shape
#labels = labels.reshape(c,)

In [116]:
# array to dataframe
#df77 = pd.DataFrame(data=a[1:,1:],index=a[1:,0], columns=a[0,1:])

In [117]:
from sklearn.metrics import mean_squared_error

In [118]:
mean_squared_error(y_test,a)

4680.5127814777352